### ISSUE TITLE
Questitems

### ISSUE THREAD

**Issue by fdellwing** [mikepauer/Carbonite.Quests#10]
For some time now, I cannot use the questitem that is pinned to the tracker. I have to use it in my inventory.

**Comment by IrcDirk** [comment]
Works fine to me just completed 10 quests with items no problem with clicking them on the tracker.

**Comment by fdellwing** [comment]
https://youtu.be/tmNH9d8pdsI

**Comment by IrcDirk** [comment]
Weird... what quest was that?

**Comment by fdellwing** [comment]
One of the karazan prequest, but it happens by all quests. This is no new problem, would say it happens for about 2 months now.

**Comment by IrcDirk** [comment]
For me all items work ok. Very weird.

**Comment by fdellwing** [comment]
It is working for my druid, maybe a DH only problem? Can you check that @IrcDirk?

**Comment by IrcDirk** [comment]
I will check this tommorow on my DH.
