### ISSUE TITLE
Quest Not in Database

### ISSUE THREAD

**Issue by newtonj14** [mikepauer/Carbonite.Quests#103]
I keep getting a quest is not in the database when trying to track dragon isle quests. I have had to move back to 100% tracking with blizzards quest log :( Icons don't show up on the map either.

**Comment by sporta06** [comment]
Having the same issue. Quests have not been showing up for quite a while now...are we the only ones that are experiencing this issue? if so, is there a way to clear out the db and re-import?

Thanks

**Comment by Fl1pp3d0ff** [comment]
Same issue here.  Still. Since I came back to the game two months ago and fresh-installed, none of the quest tracking works.. even in  August. No idea how to fix .
Dragonflight quests all show "Quest not in Database". Previous expansions work properly.
This seems to be a dragonflight-only issue.

**Comment by FelixFTW** [comment]
Anyway to make this work?  I've loved this addon since 2009 and its such a bummer now that I can't use it.  I've had to degrade to mapster which isn't even close...

**Comment by Panerdar** [comment]
Is this being worked at all?

**Comment by Panerdar** [comment]
I see someone is doing some updates to Carbonite. Is there just no intent to update this and put the Dragon flight quests in the database?

**Comment by IrcDirk** [comment]
Those quests need to be scrapped from WoWHead. No time for that right now.

**Comment by chris-arsenault** [comment]
@IrcDirk if it's easier to provide instructions on how to scrape WoWHead for them, I might be able to take on the scaping
