### ISSUE TITLE
ObjectiveTrackerFrame filckering

### ISSUE THREAD

**Issue by GeoRam2016** [mikepauer/Carbonite.Quests#118]
Hi
Is there any way to turn off this standard Blizzard quest list?
It constantly fades in and out ingame.
It's annoying in the long run.
Thank you

**Comment by GeoRam2016** [comment]
https://www.directupload.eu/file/u/79648/xo9k9csf_jpg.htm

**Comment by IrcDirk** [comment]
Im searching fix for it.

**Comment by IrcDirk** [comment]
Hmmm... after last update it seems it doesnt do that anymore.

**Comment by GeoRam2016** [comment]
@IrcDirk 
Thanks for the update.
Work great
Thank you
