### ISSUE TITLE
NxQuest.lua:9424: Usage: GetTaskInfo(questID)

### ISSUE THREAD

**Issue by Thrumbar** [mikepauer/Carbonite.Quests#125]
1967x Carbonite.Quests/NxQuest.lua:9424: Usage: GetTaskInfo(questID)
[string "=[C]"]: in function `GetTaskInfo'
[string "@Carbonite.Quests/NxQuest.lua"]:9424: in function `UpdateList'
[string "@Carbonite.Quests/NxQuest.lua"]:9069: in function `func'
[string "@Carbonite/Libs/AceTimer-3.0-17/AceTimer-3.0.lua"]:57: in function <Carbonite/Libs/AceTimer-3.0/AceTimer-3.0.lua:50>

Locals:
(*temporary) = nil

Doing this brings back the quest watch window.  Further checking and other errors still there but quest watch and tracking seem to work,,

9424 --              local inArea, onMap, numObjectives = GetTaskInfo(questId)
9425 --              tasks[questId] = true

**Comment by IrcDirk** [comment]
Hmmm? I dont get this errror... weird.

**Comment by Thrumbar** [comment]
Will refresh all my Carbonite installs and recheck as soon as get back home.

On October 23, 2024 1:22:34 AM CDT, IrcDirk ***@***.***> wrote:
>Hmmm? I dont get this errror... weird.
>
>-- 
>Reply to this email directly or view it on GitHub:
>https://github.com/mikepauer/Carbonite.Quests/issues/125#issuecomment-2431015732
>You are receiving this because you authored the thread.
>
>Message ID: ***@***.***>
James T Nolan

**Comment by Thrumbar** [comment]
It started with the 10.0.5 that dropped today in US..

On October 23, 2024 1:22:34 AM CDT, IrcDirk ***@***.***> wrote:
>Hmmm? I dont get this errror... weird.
>
>-- 
>Reply to this email directly or view it on GitHub:
>https://github.com/mikepauer/Carbonite.Quests/issues/125#issuecomment-2431015732
>You are receiving this because you authored the thread.
>
>Message ID: ***@***.***>
James T Nolan

**Comment by IrcDirk** [comment]
More errors in Quest module... but already fixed them :D
