### ISSUE TITLE
Quest use item does not appear with world quest

### ISSUE THREAD

**Issue by Thrumbar** [mikepauer/Carbonite.Quests#2]
Quest is Storming the Portals in Stormheim "Gates of Valor" area.

This if Carbonite Quest
 https://1drv.ms/i/s!Ai8SfAzON-JQgYMY6LD8Dzk_HbS4NA

With Blizzard Quest
https://1drv.ms/i/s!Ai8SfAzON-JQgYMXCIvtoWxfZ82A0A

**Comment by IrcDirk** [comment]
Yes i know this. For bonus quests and world quests there is no function to handle items. Will see what i can do with that in spare time.
