### ISSUE TITLE
26x Carbonite.Quests\NxQuest.lua:9066: bad argument #4 to 'format' (string expected, got nil)

### ISSUE THREAD

**Issue by Swirrel** [mikepauer/Carbonite.Quests#20]
Evening.

Due to a guild achievement I tonight decided to make a Goblin DK and use my 100 boost that I got when I bought Legion. Entering World of Warcraft landed me with a Carbonite Quest bug.
It kept counting from 1 to 100+, but as I had to setup Elvui and do a few /reloads it's now stopped on bug 26 (or however to say that)..
As my DK "landed" on a boat when I entered game I had an npc I could talk to and the second I did that the bug stopped repeating it self.

Bug:
26x Carbonite.Quests\NxQuest.lua:9066: bad argument #4 to 'format' (string expected, got nil)
[C]: in function `format'
Carbonite.Quests\NxQuest.lua:9066: in function `UpdateList'
Carbonite.Quests\NxQuest.lua:8892: in function `func'
Carbonite\Libs\AceTimer-3.0\AceTimer-3.0-17.lua:55: in function <Carbonite\Libs\AceTimer-3.0\AceTimer-3.0.lua:48>

Locals:
(*temporary) = "|cffffffff%d/%d %s"
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = "string expected, got nil"

I didn't change anything else than describe above. It just stopped.
So technically my new character went from being a trial toon to a lvl 100 toon. 

Cheers Jag.

Ps. Thank you.

![wowscrnshot_111317_002635](https://user-images.githubusercontent.com/31900265/32704751-a7385aa0-c80a-11e7-92bd-0ae22d2b50f1.jpg)

**Comment by Swirrel** [comment]
Finising my "introduction abilities" thingie, I get the error again:
22x Carbonite.Quests\NxQuest.lua:9066: bad argument #4 to 'format' (string expected, got nil)
[C]: in function `format'
Carbonite.Quests\NxQuest.lua:9066: in function `UpdateList'
Carbonite.Quests\NxQuest.lua:8892: in function `func'
Carbonite\Libs\AceTimer-3.0\AceTimer-3.0-17.lua:55: in function <Carbonite\Libs\AceTimer-3.0\AceTimer-3.0.lua:48>

Locals:
(*temporary) = "|cffffffff%d/%d %s"
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = "string expected, got nil"


It just keeps on counting, now on 80+

**Comment by Swirrel** [comment]
I don't know if it's worth mentioning, but 2-3 days ago I restored a Goblin Mage I had deleted shortly after Legion launched. I haven't had that carbonite quest bug on her and now she's 108, where as the Goblin DK is just 100

**Comment by IrcDirk** [comment]
Yep... i did saw this one time when using Class Trial. Will make fix for this in spare time.

**Comment by IrcDirk** [comment]
Ok, should be fixed now.

**Comment by Swirrel** [comment]
It works.

Thank you for fixing it so quickly :)
