### ISSUE TITLE
Quest objectives not showing as complete until reload

### ISSUE THREAD

**Issue by Thrumbar** [mikepauer/Carbonite.Quests#24]
Doing the Originals and killed mob but objective shows as not complete.  Tooltip on mouseing over mob corpse shows objective complete and quest title says complete but the objective show as 0/1..

![wowscrnshot_111917_023421](https://user-images.githubusercontent.com/2394469/32988848-4cea8ad8-ccd2-11e7-8c33-3f70464b1fb7.jpg)

Edit: Reloading changes this and quest shows complete..

![wowscrnshot_111917_024121](https://user-images.githubusercontent.com/2394469/32988896-25afed54-ccd3-11e7-9ae8-caa104d37c0d.jpg)

**Comment by IrcDirk** [comment]
Thats in party... something is wrong with this, thought i fixed all of that, but maybe not...

**Comment by IrcDirk** [comment]
Weird all works fine in party questing...

**Comment by Thrumbar** [comment]
Changed some of my addons and is is working.  May have been a addon conflict or that I was dead at the end of the fight..  Closing
