### ISSUE TITLE
another combat lockdown error

### ISSUE THREAD

**Issue by fdellwing** [mikepauer/Carbonite.Quests#3]
```
Date: 2017-06-16 16:18:55
ID: 1
Error occured in: AddOn: Carbonite.Quests
Count: 51
Message: Note: AddOn Carbonite.Quests attempted to call a protected function (<unnamed>:SetEnabled()) during combat lockdown.
Debug:
   [C]: SetEnabled()
   ..\FrameXML\WorldMapActionButton.lua:96: UpdateCooldown()
   ..\FrameXML\WorldMapActionButton.lua:5:
      ..\FrameXML\WorldMapActionButton.lua:3
Locals:
None
AddOns:
  Swatter, v7.0.5 (<%codename%>)
  NPCScanOverlay, v7.1.0.1
  AdvancedInterfaceOptions, v1.1.4
  Babylonian, v5.1.DEV.332(/embedded)
  BagBrother, v
  Bagnon, v7.2.5
  Bartender4, v4.7.7
  BeanCounter, v7.4.5714 (TasmanianThylacine)
  brokerorderhall, vv1.1.3.70100
  Carbonite, v7.2.0
  CarboniteInfo, v7.2.0
  CarboniteNotes, v7.2.0
  CarboniteQuests, v7.2.0
  CarboniteSocial, v7.2.0
  CarboniteWarehouse, v7.2.0
  CarboniteWeekly, v7.2.0
  Configator, v5.1.DEV.406(/embedded)
  DBMCore, v7.2.7
  DBMDefaultSkin, v
  DBMSpellTimers, v
  DBMStatusBarTimers, v
  DebugLib, v5.1.DEV.337(/embedded)
  DejaCharacterStats, v725r100
  EasyObliterate, v26
  FishingBuddy, v1.7.13a
  GarrisonCommanderBroker, v2.18.2 1.1.0
  Gatherer, v7.0.5
  HandyNotes, vv1.4.13
  HandyNotesBrokenShore, vv1.18
  HandyNotesDraenorTreasures, v1.20a
  HandyNotesEphemeralCrystals, vr01
  HandyNotesEverShiftingMirror, v1.0.3
  HandyNotesHigherLearning, v7.1.0.0
  HandyNotesLegionClassOrderHalls, vv1.18
  HandyNotesLegionInstanceWorldQuests, vv1.08
  HandyNotesLegionRaresTreasures, v1.01b
  HandyNotesLorewalkers, v1
  HandyNotesLostAndFound, v1
  HandyNotesPandariaTreasures, v1.06
  HandyNotesSuramarLeylines, v1
  HandyNotesSuramarLocations, v0.0.1
  HandyNotesSuramarTelemancy, v1
  HandyNotesTimelessIsleChests, v1.17
  HandyNotesTrainers, v1.7.0
  HandyNotesWitheredArmyTraining, v1
  LibExtraTip, v5.12.DEV.423(/embedded)
  MasterPlanA, vA
  MoveAnything, v16.2.0
  NomiCakes, v7.2.5.0
  NPCScan, v7.2.0.2
  Omen, v3.1.12
  OmniCC, v7.2.0
  Overachiever, v0.99.7
  OverachieverTabs, v0.99.7
  ParagonReputation, v1.14
  Pawn, v2.2.8
  PersonalLootHelper, v1.29
  PetTracker, v7.1.4
  PetTrackerBreeds, v7.1.4
  PetTrackerConfig, v7.1.4
  PetTrackerJournal, v7.1.4
  PetTrackerSwitcher, v7.1.4
  PetTrackerUpgrades, v7.1.4
  Postal, vv3.5.8
  Prat30, vr1054      
  Prat30Libraries, v
  PremadeGroupsFilter, v1.10
  Quartz, v3.3.4
  Rarity, v1.0
  RarityOptions, v
  Recount, vv7.2.0c
  SavedInstances, v7.0.8
  setItemOrder, v
  SimpleILevel, v3.3.10
  SimpleILevelGroup, v3.3.10
  SimpleILevelResilience, v3.3.10
  SimpleILevelSocial, v3.3.10
  SlideBar, v7.0.5 (<%codename%>)
  Stubby, v7.4.5714 (TasmanianThylacine)
  TheUndermineJournal, v4.7.20170613
  TipHelper, v5.12.DEV.405(/embedded)
  TradeSkillMaster, vv3.6.28
  TradeSkillMasterAccounting, vv3.0.19
  TradeSkillMasterAppHelper, vv3.0.3
  TradeSkillMasterAuctionDB, vv3.1.17
  TradeSkillMasterAuctioning, vv3.0.15
  TradeSkillMasterShopping, vv3.4.6
  TradeSkillMasterVendoring, vv3.0.6
  WeakAuras, v2.4.3
  WorldQuestGroupFinder, v0.26
  WorldQuestTracker, v
  ZPerl, v5.3.2
  ZPerlArcaneBar, v
  ZPerlParty, v
  ZPerlPartyPet, v
  ZPerlPlayer, v
  ZPerlPlayerBuffs, v
  ZPerlPlayerPet, v
  ZPerlRaidAdmin, v
  ZPerlRaidFrames, v
  ZPerlRaidHelper, v
  ZPerlRaidMonitor, v
  ZPerlRaidPets, v
  ZPerlTarget, v
  ZPerlTargetTarget, v
  BlizRuntimeLib_deDE v7.2.5.70200 <none>
  (ck=b6d)
```

**Comment by IrcDirk** [comment]
This may be new blizz shitty changes... will check if this is something serious.

**Comment by IrcDirk** [comment]
When did this happened? Cant reproduce...

**Comment by fdellwing** [comment]
Can't remember. Happened like 2-3 times at most. Will look at the circumstances if its happening again.

**Comment by IrcDirk** [comment]
Hard to debug when i cant reproduce :( Please report back if u get this another time.

**Comment by fdellwing** [comment]
So, not the exact same error, but I'm sure its the same reason:

```
Date: 2017-06-19 07:58:06
ID: 3
Error occured in: AddOn: Carbonite.Quests
Count: 2
Message: Note: AddOn Carbonite.Quests attempted to call a protected function (<unnamed>:Hide()) during combat lockdown.
Debug:
   [C]: Hide()
   ..\FrameXML\WorldMapActionButton.lua:58: Clear()
   ..\FrameXML\WorldMapActionButton.lua:67: Refresh()
   ..\FrameXML\WorldMapActionButton.lua:19: SetMapAreaID()
   ..\FrameXML\WorldMapFrame.lua:1341: WorldMapFrame_Update()
   ..\FrameXML\WorldMapFrame.lua:2873: WorldMapFrame_UpdateMap()
   ..._ObjectiveTracker\Blizzard_BonusObjectiveTracker.lua:162: BonusObjectiveTracker_TrackWorldQuest()
   Carbonite.Quests\NxQuest.lua:7964:
      Carbonite.Quests\NxQuest.lua:7948
Locals:
None
AddOns:
  Swatter, v7.0.5 (<%codename%>)
  NPCScanOverlay, v7.1.0.1
  AdvancedInterfaceOptions, v1.1.4
  Babylonian, v5.1.DEV.332(/embedded)
  BagBrother, v
  Bagnon, v7.2.5
  Bartender4, v4.7.7
  BeanCounter, v7.4.5714 (TasmanianThylacine)
  brokerorderhall, vv1.1.3.70100
  Carbonite, v7.2.5
  CarboniteInfo, v7.2.0
  CarboniteNotes, v7.2.0
  CarboniteQuests, v7.2.5
  CarboniteSocial, v7.2.0
  CarboniteWarehouse, v7.2.0
  CarboniteWeekly, v7.2.0
  Configator, v5.1.DEV.406(/embedded)
  DBMCore, v7.2.7
  DBMDefaultSkin, v
  DBMSpellTimers, v
  DBMStatusBarTimers, v
  DebugLib, v5.1.DEV.337(/embedded)
  DejaCharacterStats, v725r100
  EasyObliterate, v26
  FishingBuddy, v1.7.13a
  GarrisonCommander, v2.18.2 70200
  GarrisonCommanderBroker, v2.18.2 1.1.0
  Gatherer, v7.0.5
  HandyNotes, vv1.4.13
  HandyNotesBrokenShore, vv1.18
  HandyNotesDraenorTreasures, v1.20a
  HandyNotesEphemeralCrystals, vr01
  HandyNotesEverShiftingMirror, v1.0.3
  HandyNotesHigherLearning, v7.1.0.0
  HandyNotesLegionClassOrderHalls, vv1.18
  HandyNotesLegionInstanceWorldQuests, vv1.08
  HandyNotesLegionRaresTreasures, v1.01b
  HandyNotesLorewalkers, v1
  HandyNotesLostAndFound, v1
  HandyNotesPandariaTreasures, v1.06
  HandyNotesSuramarLeylines, v1
  HandyNotesSuramarLocations, v0.0.1
  HandyNotesSuramarTelemancy, v1
  HandyNotesTimelessIsleChests, v1.17
  HandyNotesTrainers, v1.7.0
  HandyNotesWitheredArmyTraining, v1
  HideOrderHallBar, vv1.2.3
  LibExtraTip, v5.12.DEV.423(/embedded)
  MasterPlanA, vA
  MoveAnything, v16.2.0
  NomiCakes, v7.2.5.4
  NPCScan, v7.2.0.2
  Omen, v3.1.12
  OmniCC, v7.2.0
  OrderHallCommander, v1.3.0 70200
  Overachiever, v0.99.8
  ParagonReputation, v1.14
  Pawn, v2.2.8
  PersonalLootHelper, v1.29
  PetTracker, v7.1.4
  PetTrackerBreeds, v7.1.4
  PetTrackerConfig, v7.1.4
  PetTrackerSwitcher, v7.1.4
  PetTrackerUpgrades, v7.1.4
  Postal, vv3.5.8
  Prat30, vr1054      
  Prat30Libraries, v
  PremadeGroupsFilter, v1.11
  Quartz, v3.3.4
  Recount, vv7.2.0c
  SavedInstances, v7.0.8
  setItemOrder, v
  SimpleILevel, v3.3.10
  SimpleILevelGroup, v3.3.10
  SimpleILevelResilience, v3.3.10
  SimpleILevelSocial, v3.3.10
  SlideBar, v7.0.5 (<%codename%>)
  Stubby, v7.4.5714 (TasmanianThylacine)
  TheUndermineJournal, v4.7.20170617
  TipHelper, v5.12.DEV.405(/embedded)
  TradeSkillMaster, vv3.6.29
  TradeSkillMasterAccounting, vv3.0.19
  TradeSkillMasterAppHelper, vv3.0.3
  TradeSkillMasterAuctionDB, vv3.1.17
  TradeSkillMasterAuctioning, vv3.0.15
  TradeSkillMasterShopping, vv3.4.6
  TradeSkillMasterVendoring, vv3.0.6
  WeakAuras, v2.4.3
  WorldQuestGroupFinder, v0.26.1
  WorldQuestTracker, v
  ZPerl, v5.3.2
  ZPerlArcaneBar, v
  ZPerlParty, v
  ZPerlPartyPet, v
  ZPerlPlayer, v
  ZPerlPlayerBuffs, v
  ZPerlPlayerPet, v
  ZPerlRaidAdmin, v
  ZPerlRaidFrames, v
  ZPerlRaidHelper, v
  ZPerlRaidMonitor, v
  ZPerlRaidPets, v
  ZPerlTarget, v
  ZPerlTargetTarget, v
  BlizRuntimeLib_deDE v7.2.5.70200 <none>
  (ck=b77)
```

I got to a world quest boss in last 3-5 secs before he died and hit him. After I lootet him, I got this error.

Level 103 Tauren Druid

**Comment by IrcDirk** [comment]
Ok, thats something... will try to research this.

**Comment by fdellwing** [comment]
I cant even reproduce it myself for sure :/

**Comment by IrcDirk** [comment]
Hmmm... u dont get world quests before 110, thats weird...

**Comment by IrcDirk** [comment]
Ok, pushed some changes try again on lvling alt.

**Comment by fdellwing** [comment]
You get them, I an invasion is happening ;)

Will log on alt next invasion, but could be a few days. Have to work rest of week and will be with my girlfriend the weekend.

**Comment by fdellwing** [comment]
Will mark this as fixxed, did not happened yesterday or today. Will reopen if not fixxed,

**Comment by fdellwing** [comment]
Happened again on my alt after leaving a group.

Date: 2017-06-27 20:25:26
ID: 3
Error occured in: AddOn: Carbonite.Quests
Count: 8
Message: Note: AddOn Carbonite.Quests attempted to call a protected function (<unnamed>:Hide()) during combat lockdown.
Debug:
   [C]: Hide()
   ..\FrameXML\WorldMapActionButton.lua:58: Clear()
   ..\FrameXML\WorldMapActionButton.lua:67: Refresh()
   ..\FrameXML\WorldMapActionButton.lua:19: SetMapAreaID()
   ..\FrameXML\WorldMapFrame.lua:1341: WorldMapFrame_Update()
   ..\FrameXML\WorldMapFrame.lua:2873: WorldMapFrame_UpdateMap()
   ..\FrameXML\WorldMapFrame.lua:451:
      ..\FrameXML\WorldMapFrame.lua:435
   [C]: ?
   [C]: ?
   [C]: ?
   [C]: SetMapToCurrentZone()
   ..\FrameXML\WorldMapFrame.lua:381:
      ..\FrameXML\WorldMapFrame.lua:360
   [C]: ?
   [C]: ?
   [C]: ?
   [C]: Show()
   ..\FrameXML\UIParent.lua:2374: SetUIPanel()
   ..\FrameXML\UIParent.lua:2213: ShowUIPanel()
   ..\FrameXML\UIParent.lua:2133:
      ..\FrameXML\UIParent.lua:2129
   [C]: SetAttribute()
   ..\FrameXML\UIParent.lua:2915:
      ..\FrameXML\UIParent.lua:2903
   [C]: ?
   [C]: ?
   [C]: ?
   [C]: ShowUIPanel()
   ..\FrameXML\UIParent.lua:2899:
      ..\FrameXML\UIParent.lua:2895
   [C]: ToggleFrame()
   ..\FrameXML\WorldMapFrame.lua:263:
      ..\FrameXML\WorldMapFrame.lua:235
   [C]: ToggleWorldMap()
   [string "TOGGLEWORLDMAP"]:1:
      [string "TOGGLEWORLDMAP"]:1
Locals:
None
AddOns:
  Swatter, v7.0.5 (<%codename%>)
  NPCScanOverlay, v7.1.0.1
  AdvancedInterfaceOptions, v1.1.4
  Babylonian, v5.1.DEV.332(/embedded)
  BagBrother, v
  Bagnon, v7.2.5
  Bartender4, v4.7.7
  BeanCounter, v7.4.5714 (TasmanianThylacine)
  brokerorderhall, vv1.1.3.70100
  Carbonite, v7.2.5
  CarboniteInfo, v7.2.0
  CarboniteNotes, v7.2.0
  CarboniteQuests, v7.2.5
  CarboniteSocial, v7.2.0
  CarboniteWarehouse, v7.2.0
  CarboniteWeekly, v7.2.0
  Configator, v5.1.DEV.406(/embedded)
  DBMCore, v7.2.10
  DBMDefaultSkin, v
  DBMSpellTimers, v
  DBMStatusBarTimers, v
  DebugLib, v5.1.DEV.337(/embedded)
  DejaCharacterStats, v725r100
  EasyObliterate, v26
  FishingBuddy, v1.7.13b
  GarrisonCommander, v2.18.2 70200
  GarrisonCommanderBroker, v2.18.2 1.1.0
  Gatherer, v7.0.5
  HandyNotes, vv1.4.13
  HandyNotesBrokenShore, vv1.18
  HandyNotesDraenorTreasures, v1.20a
  HandyNotesEphemeralCrystals, vr01
  HandyNotesEverShiftingMirror, v1.0.3
  HandyNotesHigherLearning, v7.1.0.0
  HandyNotesLegionClassOrderHalls, vv1.20
  HandyNotesLegionInstanceWorldQuests, vv1.08
  HandyNotesLegionRaresTreasures, v1.01b
  HandyNotesLorewalkers, v1
  HandyNotesLostAndFound, v1
  HandyNotesPandariaTreasures, v1.06
  HandyNotesSuramarLeylines, v1
  HandyNotesSuramarLocations, v0.0.1
  HandyNotesSuramarTelemancy, v1
  HandyNotesTimelessIsleChests, v1.17
  HandyNotesTrainers, v1.7.0
  HandyNotesWitheredArmyTraining, v1
  HideOrderHallBar, vv1.2.3
  LibExtraTip, v5.12.DEV.423(/embedded)
  MasterPlanA, vA
  MoveAnything, v16.2.0
  NomiCakes, v7.2.5.4
  NPCScan, v7.2.0.2
  Omen, v3.1.12
  OmniCC, v7.2.1
  OrderHallCommander, v1.3.0 70200
  Overachiever, v0.99.8
  ParagonReputation, v1.15
  Pawn, v2.2.8
  PersonalLootHelper, v1.29
  PetTracker, v7.1.4
  PetTrackerBreeds, v7.1.4
  PetTrackerConfig, v7.1.4
  PetTrackerSwitcher, v7.1.4
  PetTrackerUpgrades, v7.1.4
  Postal, vv3.5.8
  Prat30, vr1078      
  Prat30Libraries, v
  PremadeGroupsFilter, v1.11
  Quartz, v3.3.4
  Recount, vv7.2.5a
  SavedInstances, v7.0.8
  setItemOrder, v
  SimpleILevel, v3.3.10
  SimpleILevelGroup, v3.3.10
  SimpleILevelResilience, v3.3.10
  SimpleILevelSocial, v3.3.10
  SlideBar, v7.0.5 (<%codename%>)
  Stubby, v7.4.5714 (TasmanianThylacine)
  TheUndermineJournal, v4.7.20170624
  TipHelper, v5.12.DEV.405(/embedded)
  TradeSkillMaster, vv3.6.29
  TradeSkillMasterAccounting, vv3.0.19
  TradeSkillMasterAppHelper, vv3.0.3
  TradeSkillMasterAuctionDB, vv3.1.17
  TradeSkillMasterAuctioning, vv3.0.15
  TradeSkillMasterShopping, vv3.4.6
  TradeSkillMasterVendoring, vv3.0.6
  WeakAuras, v2.4.5
  WorldQuestGroupFinder, v0.26.3
  WorldQuestTracker, v
  ZPerl, v5.3.2
  ZPerlArcaneBar, v
  ZPerlParty, v
  ZPerlPartyPet, v
  ZPerlPlayer, v
  ZPerlPlayerBuffs, v
  ZPerlPlayerPet, v
  ZPerlRaidAdmin, v
  ZPerlRaidFrames, v
  ZPerlRaidHelper, v
  ZPerlRaidMonitor, v
  ZPerlRaidPets, v
  ZPerlTarget, v
  ZPerlTargetTarget, v
  BlizRuntimeLib_deDE v7.2.5.70200 <none>
  (ck=b78)
