### ISSUE TITLE
Lag

### ISSUE THREAD

**Issue by Palonblade** [mikepauer/Carbonite.Quests#30]
I often get lag when grouped for world quests etc. If I unload Carb Quests the lag goes away. Is there any setting I can adjust or a possible fix for this? I already have changed my Broadcast after number of changes to 999, Watch delay time to 1000 and also in the Database section only load quests for 101-110. Doesn't make a difference but thought I would try.

**Comment by IrcDirk** [comment]
This is the same issue as https://github.com/mikepauer/Carbonite/issues/61, try using this settings **and tell me if this makes a difference**:

[screenshot](https://i.imgur.com/fcnCoeu.png)

**Comment by Palonblade** [comment]
I already had those 2 options disabled. Also for me it isn't necessarily when killing a mob although possibly the same underlying problem. As an example, it was happening today when doing the "Aw, Nuts!" WQ. As I was simply right clicking stuff on the ground I would occasionally lag so maybe when killing x of y or collecting x of y the quest objective updating is causing issues.

**Comment by IrcDirk** [comment]
What about disabling this?

![screenshot](https://i.imgur.com/DzlkCld.png)

**Comment by Palonblade** [comment]
Already disabled. I have only 101-110 and Level 0 enabled :(.

**Comment by IrcDirk** [comment]
Im searching for fix, but it not allways lags for me. Someone knows how to simulate it, that it will lag every time?

**Comment by Palonblade** [comment]
Unfortunately it's the same for me, it lags a bit then stops, lags a bit then stops.

**Comment by IrcDirk** [comment]
@Palonblade it might be SavedInstances here too!!! Check without SavedInstances.
