### ISSUE TITLE
Quest watch windows while grouped

### ISSUE THREAD

**Issue by Thrumbar** [mikepauer/Carbonite.Quests#31]
Having issues with the quest watch window while grouped..

https://youtu.be/O0wwTz4vB-Q

Some of the quest are on only on character and not the other.  Also the colon seperating the progress number and quest name appears and disappears as does the (+1)..

This only happens in group..

**Comment by IrcDirk** [comment]
Yes, there is a problem with quest sharing and displaying party quests. For now just disable this feature.
