### ISSUE TITLE
Carbonite Quest no longer able to link quests in chat while Elvui is enabled - but the error only mention Carbonite

### ISSUE THREAD

**Issue by IrcDirk** [mikepauer/Carbonite.Quests#36]
_From @Swirrel on March 24, 2018 15:32_

Yesterday everything was working fine. No errors, no bugs, no nothing.

Information:
Today, I see that there's an update for Elvui via the Tukui Client, so I update Elvui.
I check the Twitch Client too, but there aren't any updates for me today
I also had a driver update for my graphic card today, so I update that too.

Explanation:
I log in to wow, first my bank toon, then my main toon.. At some point I decide that I want to ask my guildies if there's anyone of them, that's not a tank, that want's to do:  [110] [The Seat of the Triumvirate: Armor of the Triumvirate] ?
I never get a reply, because no one inc. my self, can see it linked in chat. I then try to link it in a whisper and nothing shows.. No links, no errors, no bugs
Then I try and link to both the guild chat and after in a whisper: an ability from my spellbook, an item from my bag and a recipe from cooking - that works and gets linked so both my online guildies, bnet whisper (the one I linked in whisper to check if it worked there too) and my self can see them.. hmm.
I turn Elvui off, and I still can't link any of my 3 quests, not even World Quests/Invasion Quests (I tried when I was 1st in Azsuna, and 2nd in Suramar - no such luck)
I then try to link a different quest: 110 Trial of Valor: The Lost Army and I get the below error:

6x Carbonite.Quests\NxQuest.lua:6631: attempt to compare nil with number
Carbonite.Quests\NxQuest.lua:6631: in function `MakeDescLink'
Carbonite.Quests\NxQuest.lua:6460: in function `UserFunc'
Carbonite\NxUI.lua:6455: in function <Carbonite\NxUI.lua:6434>

Locals:
self = <table> {
 UpdateMenu = <function> defined @Carbonite.Quests\NxQuest.lua:5754
 Win = <table> {
 }
 Menu_OnShowHeaders = <function> defined @Carbonite.Quests\NxQuest.lua:6147
 MakeDescLink = <function> defined @Carbonite.Quests\NxQuest.lua:6613
 Menu_OnTrackNone = <function> defined @Carbonite.Quests\NxQuest.lua:6394
 Menu_OnWatchAll = <function> defined @Carbonite.Quests\NxQuest.lua:6240
 TabSelected = 1
 Menu_OnHighPri = <function> defined @Carbonite.Quests\NxQuest.lua:6138
 FilterOnEditFocusLost = <function> defined @Carbonite.Quests\NxQuest.lua:6059
 Menu_OnShowAllQuests = <function> defined @Carbonite.Quests\NxQuest.lua:6161
 Menu_OnShowFinished = <function> defined @Carbonite.Quests\NxQuest.lua:6181
 Menu_OnGoto = <function> defined @Carbonite.Quests\NxQuest.lua:6119
 MenuIShare = <table> {
 }
 DetailsFrm = NxQuestD {
 }
 MenuItems4 = <table> {
 }
 MenuItems3 = <table> {
 }
 MenuItems2 = <table> {
 }
 Menu_OnCompleted = <function> defined @Carbonite.Quests\NxQuest.lua:6196
 Select = <function> defined @Carbonite.Quests\NxQuest.lua:5979
 OnDetailsSetSize = <function> defined @Carbonite.Quests\NxQuest.lua:8099
 Open = <function> defined @Carbonite.Quests\NxQuest.lua:5442
 OnTabBar = <function> defined @Carbonite.Quests\NxQuest.lua:6094
 AttachFrames = <function> defined @Carbonite.Quests\NxQuest.lua:5730
 Menu = <table> {
 }
 FilterOnTextChanged = <function> defined @Carbonite.Quests\NxQuest.lua:6069
 List = <table> {
 }
 FilterOnEditFocusGained = <function> defined @Carbonite.Quests\NxQuest.lua:6044
 Filters = <table> {
 }
 FilterDescEsc = "Search: %[click%]"
 FilterDesc = "Search: [click]"
 FilterFrm = NxQuestFilter {
 }
 MenuItems1 = <table> {
 }
 Menu_OnShowParty = <function> defined @Carbonite.Quests\NxQuest.lua:6191
 QOpts = <table> {
 }
 OnSendQuestInfoTimer = <function> defined @Carbonite.Quests\NxQuest.lua:6297
 Menu_OnAbandon = <function> defined @Carbonite.Quests\NxQuest.lua:6361
 Menu_OnHistoryRemoveAll = <function> defined @Carbonite.Quests\NxQuest.lua:6219
 ToggleWatch = <function> defined @Carbonite.Quests\NxQuest.lua:6558
 Menu_OnShowOnlyDailies = <function> defined @Carbonite.Quests\NxQuest.lua:6186
 DetailsSetWidth = <function> defined @Carbonite.Quests\NxQuest.lua:8121
 Menu_OnShowAllZones = <function> defined @Carbonite.Quests\NxQuest.lua:6176
 Opened = true
 Update = <function> defined @Carbonite.Quests\NxQuest.lua:6823
 CheckShow = <function> defined @Carbonite.Quests\NxQuest.lua:7540
 LogUpdate = <function> defined @Carbonite.Quests\NxQuest.lua:6769
 FilterOnEscapePressed = <function> defined @Carbonite.Quests\NxQuest.lua:6083
 Menu_OnShare = <function> defined @Carbonite.Quests\NxQuest.lua:6345
 Menu_OnShowHighLevel = <function> defined @Carbonite.Quests\NxQuest.lua:6171
 SendQuestInfo = <function> defined @Carbonite.Quests\NxQuest.lua:6274
 Menu_OnSortWatched = <function> defined @Carbonite.Quests\NxQuest.lua:6235
 Refresh = <function> defined @Carbonite.Quests\NxQuest.lua:6659
 GetCurSelected = <function> defined @Carbonite.Quests\NxQuest.lua:6005
 FilterOnEnterPressed = <function> defined @Carbonite.Quests\NxQuest.lua:6078
 OnListEvent = <function> defined @Carbonite.Quests\NxQuest.lua:6403
 Menu_OnSendQInfo = <function> defined @Carbonite.Quests\NxQuest.lua:6264
 Menu_OnShowObjectives = <function> defined @Carbonite.Quests\NxQuest.lua:6154
 ShowAllZones = false
 Menu_OnShowLowLevel = <function> defined @Ad

And "big sigh"... I land, HS to my Garrison for easy log out/log in/reloads
I disable all addons for All toons and do a /reload
I enable Carbonite Maps and Carbonite Quest, /reload and try to link in guild chat. That works.
I disable Carbonite Maps and Carbonite Quest and Enables Elvui + Elvui Config and /reload and link in chat - that works. 
I enable Carbonite Maps + Carbonite Quest along with Elvui, Elvui Config then /reload and try to link in chat - that doesn't work. I then try to link the 110 Trial of Valor Quest and get the above error.
I disable Elvui and Elvui Config leaving Carbonite Maps and Quests on do a /reload and try to link the 110 Trial of Valor and get the above error again.
I've established that Elvui works without Carbonite and Carbonite works without Elvui and both works together IF I don't link any quests in any chat, but that I can link anything else with all addons on so long as it's not a quest that I link.
While having Carbonite Maps + Carbonite Quest on I enabled 2-10 other different addons (atlastloot have sub addons for each expansion we've had) that wasn't Carbonite or Elvui and I still couldn't get the quests to be linked in guild chat, whisper chat or general chat.
I turn Carbonite Maps + Carbonite Quest off and turn Elvui + Elvui Config on while having 2-10 of the same mentioned different addons turned on and I can link quests in guild chat, whisper chat and general chat.
Right now, I have all my addons turned on and so I'm just not linking quests in chat.
1: It's not popping up
2: I get an error with a specific quest

I'll be posting this wall of text on the Elvui Forum/gitlab too. and throw in the info that the post have been posted to both "forums".

I'm sorry for the wall of text, but I'm merely trying to provide as much detail as I can.

Any help would be highly appreciated. Thank you
Swirrel.

_Copied from original issue: mikepauer/Carbonite#81_

**Comment by IrcDirk** [comment]
Pushed fix for this issue. Blizz made undocumented change in 7.3 with quest strings.

**Comment by Swirrel** [comment]
The push worked for my quests... So thank you for that.

However, when I try to link Trial of Valor: The Lost Army, to my guild chat, nothing goes into the chat typing box (the one that you open by hitting Enter on your keyboard and type in).
When I try to link Trial of Valor I get this error:
1x Carbonite.Quests\NxQuest.lua:6631: attempt to compare nil with number
Carbonite.Quests\NxQuest.lua:6631: in function `MakeDescLink'
Carbonite.Quests\NxQuest.lua:6460: in function `UserFunc'
Carbonite\NxUI.lua:6455: in function <Carbonite\NxUI.lua:6434>

Locals:
self = <table> {
 UpdateMenu = <function> defined @Carbonite.Quests\NxQuest.lua:5754
 Win = <table> {
 }
 Menu_OnShowHeaders = <function> defined @Carbonite.Quests\NxQuest.lua:6147
 MakeDescLink = <function> defined @Carbonite.Quests\NxQuest.lua:6613
 Menu_OnTrackNone = <function> defined @Carbonite.Quests\NxQuest.lua:6394
 Menu_OnWatchAll = <function> defined @Carbonite.Quests\NxQuest.lua:6240
 TabSelected = 1
 Menu_OnHighPri = <function> defined @Carbonite.Quests\NxQuest.lua:6138
 FilterOnEditFocusLost = <function> defined @Carbonite.Quests\NxQuest.lua:6059
 Menu_OnShowAllQuests = <function> defined @Carbonite.Quests\NxQuest.lua:6161
 Menu_OnShowFinished = <function> defined @Carbonite.Quests\NxQuest.lua:6181
 Menu_OnGoto = <function> defined @Carbonite.Quests\NxQuest.lua:6119
 MenuIShare = <table> {
 }
 DetailsFrm = NxQuestD {
 }
 MenuItems4 = <table> {
 }
 MenuItems3 = <table> {
 }
 MenuItems2 = <table> {
 }
 Menu_OnCompleted = <function> defined @Carbonite.Quests\NxQuest.lua:6196
 Select = <function> defined @Carbonite.Quests\NxQuest.lua:5979
 OnDetailsSetSize = <function> defined @Carbonite.Quests\NxQuest.lua:8099
 Open = <function> defined @Carbonite.Quests\NxQuest.lua:5442
 OnTabBar = <function> defined @Carbonite.Quests\NxQuest.lua:6094
 AttachFrames = <function> defined @Carbonite.Quests\NxQuest.lua:5730
 Menu = <table> {
 }
 FilterOnTextChanged = <function> defined @Carbonite.Quests\NxQuest.lua:6069
 List = <table> {
 }
 FilterOnEditFocusGained = <function> defined @Carbonite.Quests\NxQuest.lua:6044
 Filters = <table> {
 }
 FilterDescEsc = "Search: %[click%]"
 FilterDesc = "Search: [click]"
 FilterFrm = NxQuestFilter {
 }
 MenuItems1 = <table> {
 }
 Menu_OnShowParty = <function> defined @Carbonite.Quests\NxQuest.lua:6191
 QOpts = <table> {
 }
 OnSendQuestInfoTimer = <function> defined @Carbonite.Quests\NxQuest.lua:6297
 Menu_OnAbandon = <function> defined @Carbonite.Quests\NxQuest.lua:6361
 Menu_OnHistoryRemoveAll = <function> defined @Carbonite.Quests\NxQuest.lua:6219
 ToggleWatch = <function> defined @Carbonite.Quests\NxQuest.lua:6558
 Menu_OnShowOnlyDailies = <function> defined @Carbonite.Quests\NxQuest.lua:6186
 DetailsSetWidth = <function> defined @Carbonite.Quests\NxQuest.lua:8121
 Menu_OnShowAllZones = <function> defined @Carbonite.Quests\NxQuest.lua:6176
 Opened = true
 Update = <function> defined @Carbonite.Quests\NxQuest.lua:6823
 CheckShow = <function> defined @Carbonite.Quests\NxQuest.lua:7540
 LogUpdate = <function> defined @Carbonite.Quests\NxQuest.lua:6769
 FilterOnEscapePressed = <function> defined @Carbonite.Quests\NxQuest.lua:6083
 Menu_OnShare = <function> defined @Carbonite.Quests\NxQuest.lua:6345
 Menu_OnShowHighLevel = <function> defined @Carbonite.Quests\NxQuest.lua:6171
 SendQuestInfo = <function> defined @Carbonite.Quests\NxQuest.lua:6274
 Menu_OnSortWatched = <function> defined @Carbonite.Quests\NxQuest.lua:6235
 Refresh = <function> defined @Carbonite.Quests\NxQuest.lua:6659
 GetCurSelected = <function> defined @Carbonite.Quests\NxQuest.lua:6005
 FilterOnEnterPressed = <function> defined @Carbonite.Quests\NxQuest.lua:6078
 OnListEvent = <function> defined @Carbonite.Quests\NxQuest.lua:6403
 Menu_OnSendQInfo = <function> defined @Carbonite.Quests\NxQuest.lua:6264
 Menu_OnShowObjectives = <function> defined @Carbonite.Quests\NxQuest.lua:6154
 ShowAllZones = false
 Menu_OnShowLowLevel = <function> defined @Ad

**Comment by Swirrel** [comment]
Trying to link: The Soulhunter that's also a raid quest (I only have raid quests left on my main toon^^), I get below error:

1x Carbonite.Quests\NxQuest.lua:6631: attempt to compare nil with number
Carbonite.Quests\NxQuest.lua:6631: in function `MakeDescLink'
Carbonite.Quests\NxQuest.lua:6460: in function `UserFunc'
Carbonite\NxUI.lua:6455: in function <Carbonite\NxUI.lua:6434>

Locals:
self = <table> {
 UpdateMenu = <function> defined @Carbonite.Quests\NxQuest.lua:5754
 Win = <table> {
 }
 Menu_OnShowHeaders = <function> defined @Carbonite.Quests\NxQuest.lua:6147
 MakeDescLink = <function> defined @Carbonite.Quests\NxQuest.lua:6613
 Menu_OnTrackNone = <function> defined @Carbonite.Quests\NxQuest.lua:6394
 Menu_OnWatchAll = <function> defined @Carbonite.Quests\NxQuest.lua:6240
 TabSelected = 1
 Menu_OnHighPri = <function> defined @Carbonite.Quests\NxQuest.lua:6138
 FilterOnEditFocusLost = <function> defined @Carbonite.Quests\NxQuest.lua:6059
 Menu_OnShowAllQuests = <function> defined @Carbonite.Quests\NxQuest.lua:6161
 Menu_OnShowFinished = <function> defined @Carbonite.Quests\NxQuest.lua:6181
 Menu_OnGoto = <function> defined @Carbonite.Quests\NxQuest.lua:6119
 MenuIShare = <table> {
 }
 DetailsFrm = NxQuestD {
 }
 MenuItems4 = <table> {
 }
 MenuItems3 = <table> {
 }
 MenuItems2 = <table> {
 }
 Menu_OnCompleted = <function> defined @Carbonite.Quests\NxQuest.lua:6196
 Select = <function> defined @Carbonite.Quests\NxQuest.lua:5979
 OnDetailsSetSize = <function> defined @Carbonite.Quests\NxQuest.lua:8099
 Open = <function> defined @Carbonite.Quests\NxQuest.lua:5442
 OnTabBar = <function> defined @Carbonite.Quests\NxQuest.lua:6094
 AttachFrames = <function> defined @Carbonite.Quests\NxQuest.lua:5730
 Menu = <table> {
 }
 FilterOnTextChanged = <function> defined @Carbonite.Quests\NxQuest.lua:6069
 List = <table> {
 }
 FilterOnEditFocusGained = <function> defined @Carbonite.Quests\NxQuest.lua:6044
 Filters = <table> {
 }
 FilterDescEsc = "Search: %[click%]"
 FilterDesc = "Search: [click]"
 FilterFrm = NxQuestFilter {
 }
 MenuItems1 = <table> {
 }
 Menu_OnShowParty = <function> defined @Carbonite.Quests\NxQuest.lua:6191
 QOpts = <table> {
 }
 OnSendQuestInfoTimer = <function> defined @Carbonite.Quests\NxQuest.lua:6297
 Menu_OnAbandon = <function> defined @Carbonite.Quests\NxQuest.lua:6361
 Menu_OnHistoryRemoveAll = <function> defined @Carbonite.Quests\NxQuest.lua:6219
 ToggleWatch = <function> defined @Carbonite.Quests\NxQuest.lua:6558
 Menu_OnShowOnlyDailies = <function> defined @Carbonite.Quests\NxQuest.lua:6186
 DetailsSetWidth = <function> defined @Carbonite.Quests\NxQuest.lua:8121
 Menu_OnShowAllZones = <function> defined @Carbonite.Quests\NxQuest.lua:6176
 Opened = true
 Update = <function> defined @Carbonite.Quests\NxQuest.lua:6823
 CheckShow = <function> defined @Carbonite.Quests\NxQuest.lua:7540
 LogUpdate = <function> defined @Carbonite.Quests\NxQuest.lua:6769
 FilterOnEscapePressed = <function> defined @Carbonite.Quests\NxQuest.lua:6083
 Menu_OnShare = <function> defined @Carbonite.Quests\NxQuest.lua:6345
 Menu_OnShowHighLevel = <function> defined @Carbonite.Quests\NxQuest.lua:6171
 SendQuestInfo = <function> defined @Carbonite.Quests\NxQuest.lua:6274
 Menu_OnSortWatched = <function> defined @Carbonite.Quests\NxQuest.lua:6235
 Refresh = <function> defined @Carbonite.Quests\NxQuest.lua:6659
 GetCurSelected = <function> defined @Carbonite.Quests\NxQuest.lua:6005
 FilterOnEnterPressed = <function> defined @Carbonite.Quests\NxQuest.lua:6078
 OnListEvent = <function> defined @Carbonite.Quests\NxQuest.lua:6403
 Menu_OnSendQInfo = <function> defined @Carbonite.Quests\NxQuest.lua:6264
 Menu_OnShowObjectives = <function> defined @Carbonite.Quests\NxQuest.lua:6154
 ShowAllZones = false
 Menu_OnShowLowLevel = <function> defined @Ad

The errors may be entirely the same (I haven't checked tbh), but I did try to link 2 raid quests, for 2 different raids. One has been in my questlog for a VERY long time and the other is less than a week old (old for me that is)

**Comment by IrcDirk** [comment]
Try again now.

**Comment by Swirrel** [comment]
I saw that there was another push for Carbonite Quest through the twitch client, so I updated that, logged in to wow on my main toon and tried to link the Trial of Valor: The Lost Army again, and got below error:

1x Carbonite.Quests\NxQuest.lua:6631: attempt to compare nil with number
Carbonite.Quests\NxQuest.lua:6631: in function `MakeDescLink'
Carbonite.Quests\NxQuest.lua:6460: in function `UserFunc'
Carbonite\NxUI.lua:6455: in function <Carbonite\NxUI.lua:6434>

Locals:
self = <table> {
 UpdateMenu = <function> defined @Carbonite.Quests\NxQuest.lua:5754
 Win = <table> {
 }
 Menu_OnShowHeaders = <function> defined @Carbonite.Quests\NxQuest.lua:6147
 MakeDescLink = <function> defined @Carbonite.Quests\NxQuest.lua:6613
 Menu_OnTrackNone = <function> defined @Carbonite.Quests\NxQuest.lua:6394
 Menu_OnWatchAll = <function> defined @Carbonite.Quests\NxQuest.lua:6240
 TabSelected = 1
 Menu_OnHighPri = <function> defined @Carbonite.Quests\NxQuest.lua:6138
 FilterOnEditFocusLost = <function> defined @Carbonite.Quests\NxQuest.lua:6059
 Menu_OnShowAllQuests = <function> defined @Carbonite.Quests\NxQuest.lua:6161
 Menu_OnShowFinished = <function> defined @Carbonite.Quests\NxQuest.lua:6181
 Menu_OnGoto = <function> defined @Carbonite.Quests\NxQuest.lua:6119
 MenuIShare = <table> {
 }
 DetailsFrm = NxQuestD {
 }
 MenuItems4 = <table> {
 }
 MenuItems3 = <table> {
 }
 MenuItems2 = <table> {
 }
 Menu_OnCompleted = <function> defined @Carbonite.Quests\NxQuest.lua:6196
 Select = <function> defined @Carbonite.Quests\NxQuest.lua:5979
 OnDetailsSetSize = <function> defined @Carbonite.Quests\NxQuest.lua:8103
 Open = <function> defined @Carbonite.Quests\NxQuest.lua:5442
 OnTabBar = <function> defined @Carbonite.Quests\NxQuest.lua:6094
 AttachFrames = <function> defined @Carbonite.Quests\NxQuest.lua:5730
 Menu = <table> {
 }
 FilterOnTextChanged = <function> defined @Carbonite.Quests\NxQuest.lua:6069
 List = <table> {
 }
 FilterOnEditFocusGained = <function> defined @Carbonite.Quests\NxQuest.lua:6044
 Filters = <table> {
 }
 FilterDescEsc = "Search: %[click%]"
 FilterDesc = "Search: [click]"
 FilterFrm = NxQuestFilter {
 }
 MenuItems1 = <table> {
 }
 Menu_OnShowParty = <function> defined @Carbonite.Quests\NxQuest.lua:6191
 QOpts = <table> {
 }
 OnSendQuestInfoTimer = <function> defined @Carbonite.Quests\NxQuest.lua:6297
 Menu_OnAbandon = <function> defined @Carbonite.Quests\NxQuest.lua:6361
 Menu_OnHistoryRemoveAll = <function> defined @Carbonite.Quests\NxQuest.lua:6219
 ToggleWatch = <function> defined @Carbonite.Quests\NxQuest.lua:6558
 Menu_OnShowOnlyDailies = <function> defined @Carbonite.Quests\NxQuest.lua:6186
 DetailsSetWidth = <function> defined @Carbonite.Quests\NxQuest.lua:8125
 Menu_OnShowAllZones = <function> defined @Carbonite.Quests\NxQuest.lua:6176
 Opened = true
 Update = <function> defined @Carbonite.Quests\NxQuest.lua:6827
 CheckShow = <function> defined @Carbonite.Quests\NxQuest.lua:7544
 LogUpdate = <function> defined @Carbonite.Quests\NxQuest.lua:6773
 FilterOnEscapePressed = <function> defined @Carbonite.Quests\NxQuest.lua:6083
 Menu_OnShare = <function> defined @Carbonite.Quests\NxQuest.lua:6345
 Menu_OnShowHighLevel = <function> defined @Carbonite.Quests\NxQuest.lua:6171
 SendQuestInfo = <function> defined @Carbonite.Quests\NxQuest.lua:6274
 Menu_OnSortWatched = <function> defined @Carbonite.Quests\NxQuest.lua:6235
 Refresh = <function> defined @Carbonite.Quests\NxQuest.lua:6663
 GetCurSelected = <function> defined @Carbonite.Quests\NxQuest.lua:6005
 FilterOnEnterPressed = <function> defined @Carbonite.Quests\NxQuest.lua:6078
 OnListEvent = <function> defined @Carbonite.Quests\NxQuest.lua:6403
 Menu_OnSendQInfo = <function> defined @Carbonite.Quests\NxQuest.lua:6264
 Menu_OnShowObjectives = <function> defined @Carbonite.Quests\NxQuest.lua:6154
 ShowAllZones = false
 Menu_OnShowLowLevel = <function> defined @Ad

Trying to link: The Soulhunter I get below error:

1x Carbonite.Quests\NxQuest.lua:6631: attempt to compare nil with number
Carbonite.Quests\NxQuest.lua:6631: in function `MakeDescLink'
Carbonite.Quests\NxQuest.lua:6460: in function `UserFunc'
Carbonite\NxUI.lua:6455: in function <Carbonite\NxUI.lua:6434>

Locals:
self = <table> {
 UpdateMenu = <function> defined @Carbonite.Quests\NxQuest.lua:5754
 Win = <table> {
 }
 Menu_OnShowHeaders = <function> defined @Carbonite.Quests\NxQuest.lua:6147
 MakeDescLink = <function> defined @Carbonite.Quests\NxQuest.lua:6613
 Menu_OnTrackNone = <function> defined @Carbonite.Quests\NxQuest.lua:6394
 Menu_OnWatchAll = <function> defined @Carbonite.Quests\NxQuest.lua:6240
 TabSelected = 1
 Menu_OnHighPri = <function> defined @Carbonite.Quests\NxQuest.lua:6138
 FilterOnEditFocusLost = <function> defined @Carbonite.Quests\NxQuest.lua:6059
 Menu_OnShowAllQuests = <function> defined @Carbonite.Quests\NxQuest.lua:6161
 Menu_OnShowFinished = <function> defined @Carbonite.Quests\NxQuest.lua:6181
 Menu_OnGoto = <function> defined @Carbonite.Quests\NxQuest.lua:6119
 MenuIShare = <table> {
 }
 DetailsFrm = NxQuestD {
 }
 MenuItems4 = <table> {
 }
 MenuItems3 = <table> {
 }
 MenuItems2 = <table> {
 }
 Menu_OnCompleted = <function> defined @Carbonite.Quests\NxQuest.lua:6196
 Select = <function> defined @Carbonite.Quests\NxQuest.lua:5979
 OnDetailsSetSize = <function> defined @Carbonite.Quests\NxQuest.lua:8103
 Open = <function> defined @Carbonite.Quests\NxQuest.lua:5442
 OnTabBar = <function> defined @Carbonite.Quests\NxQuest.lua:6094
 AttachFrames = <function> defined @Carbonite.Quests\NxQuest.lua:5730
 Menu = <table> {
 }
 FilterOnTextChanged = <function> defined @Carbonite.Quests\NxQuest.lua:6069
 List = <table> {
 }
 FilterOnEditFocusGained = <function> defined @Carbonite.Quests\NxQuest.lua:6044
 Filters = <table> {
 }
 FilterDescEsc = "Search: %[click%]"
 FilterDesc = "Search: [click]"
 FilterFrm = NxQuestFilter {
 }
 MenuItems1 = <table> {
 }
 Menu_OnShowParty = <function> defined @Carbonite.Quests\NxQuest.lua:6191
 QOpts = <table> {
 }
 OnSendQuestInfoTimer = <function> defined @Carbonite.Quests\NxQuest.lua:6297
 Menu_OnAbandon = <function> defined @Carbonite.Quests\NxQuest.lua:6361
 Menu_OnHistoryRemoveAll = <function> defined @Carbonite.Quests\NxQuest.lua:6219
 ToggleWatch = <function> defined @Carbonite.Quests\NxQuest.lua:6558
 Menu_OnShowOnlyDailies = <function> defined @Carbonite.Quests\NxQuest.lua:6186
 DetailsSetWidth = <function> defined @Carbonite.Quests\NxQuest.lua:8125
 Menu_OnShowAllZones = <function> defined @Carbonite.Quests\NxQuest.lua:6176
 Opened = true
 Update = <function> defined @Carbonite.Quests\NxQuest.lua:6827
 CheckShow = <function> defined @Carbonite.Quests\NxQuest.lua:7544
 LogUpdate = <function> defined @Carbonite.Quests\NxQuest.lua:6773
 FilterOnEscapePressed = <function> defined @Carbonite.Quests\NxQuest.lua:6083
 Menu_OnShare = <function> defined @Carbonite.Quests\NxQuest.lua:6345
 Menu_OnShowHighLevel = <function> defined @Carbonite.Quests\NxQuest.lua:6171
 SendQuestInfo = <function> defined @Carbonite.Quests\NxQuest.lua:6274
 Menu_OnSortWatched = <function> defined @Carbonite.Quests\NxQuest.lua:6235
 Refresh = <function> defined @Carbonite.Quests\NxQuest.lua:6663
 GetCurSelected = <function> defined @Carbonite.Quests\NxQuest.lua:6005
 FilterOnEnterPressed = <function> defined @Carbonite.Quests\NxQuest.lua:6078
 OnListEvent = <function> defined @Carbonite.Quests\NxQuest.lua:6403
 Menu_OnSendQInfo = <function> defined @Carbonite.Quests\NxQuest.lua:6264
 Menu_OnShowObjectives = <function> defined @Carbonite.Quests\NxQuest.lua:6154
 ShowAllZones = false
 Menu_OnShowLowLevel = <function> defined @Ad

**Comment by Swirrel** [comment]
[Antorus, the Burning Throne: Dark Passage] (mythic difficulty)
[110] [The Seat of the Triumvirate: Armor of the Triumvirate] 
Linking those 2 works without a hitch.
![image](https://user-images.githubusercontent.com/31900265/37964887-592f23de-31c3-11e8-8c50-4aa6091ad2a5.png)

**Comment by Swirrel** [comment]
Linking The Soulhunter and the Trial of Valor quests can be done by using Blizzards questlog that I got on 'speed dial'
![image](https://user-images.githubusercontent.com/31900265/37964972-b5a06e5c-31c3-11e8-9681-976cf25600f7.png)

**Comment by IrcDirk** [comment]
Try again. Now it should work.

**Comment by Swirrel** [comment]
Will do, as soon as I log in again. My browser had a spout of let's refresh, not work, start in safe mode and fuck up your settings, so had to reboot.

**Comment by IrcDirk** [comment]
Are u sure u updated it and restart wow?

**Comment by Swirrel** [comment]
blah... the update... 2 seconds

**Comment by Swirrel** [comment]
nothing on twitch... dammit... remind me again, how I get the new update you just did

**Comment by Swirrel** [comment]
So I downloaded the Carbonite Quest master from here on github, unpacked the folder, opend it and copied over the files to the correct folder

**Comment by IrcDirk** [comment]
Ohhh... shit. U need to wait till Twitch accepts it or download from this repo using **Clone or Download** => **Download Zip**

**Comment by Swirrel** [comment]
I did that.

And now it's working. I can link the 2 very stubborn quests that I previously couldn't link, to guild chat.

You're a darling. Thank you so much!

**Comment by Swirrel** [comment]
Carbonite Quest issue - solved
BankItems issue - solved
Kitchen Zink issue - solved
Board member, housing association issue - solved
Firefox issue and saved new profile - solved
New pettracker issue on DK - new, not solved (yet)

Let's hope nothing else pops up any time soon.

**Comment by Swirrel** [comment]
Issue can be closed as issue was solved. Thanks to a very persistent IrcDirk
