### ISSUE TITLE
The Deaths of Chromie

### ISSUE THREAD

**Issue by fdellwing** [mikepauer/Carbonite.Quests#4]
This is probably a hard one, dont know if Carbonite can this:

The szenario ist timed to 15 minutes for the bonus task (you can get additional time for the main task). It would be nice to see the live timer in Carbonite aswell. Otherwise I have to use default quest tracker for this szenario.

**Comment by IrcDirk** [comment]
Does any one knows other scenario with timer?

**Comment by fdellwing** [comment]
I dont know of any scenario, but M+ (aka Challenge) Dungeons have a similar mechanic?

**Comment by mikepauer** [comment]
Done.

**Comment by IrcDirk** [comment]
@mikepauer next time assign yourself to issue u are working on :) i will do this in future too.

**Comment by mikepauer** [comment]
There was no working on :P I saw the request when I woke up and finished it about 1.5 minutes later
