### ISSUE TITLE
Quest Log opens map in background and Log is blank if using blizzard quest log.

### ISSUE THREAD

**Issue by SteveEbey73742** [mikepauer/Carbonite.Quests#42]
My wife prefers the blizzard log, and when she uses L to open it, the empty log opens, with the carbonite map appearing behind it.  I use the carbonite log, and when I press L, I get the quest log, and I also get the map appearing behind it.

**Comment by IrcDirk** [comment]
Yes i saw that and fix is comming.

**Comment by IrcDirk** [comment]
Should be fixed now.

**Comment by SteveEbey73742** [comment]
sort of. the map is gone, if you bring up carbonite log. if she tried to bring up blizzard log, the following:

Date: 2018-07-23 15:25:23
ID: 1
Error occured in: Global
Count: 1
Message: ..\AddOns\Carbonite.Quests\NxQuest.lua line 5832:
   attempt to call global 'ShowQuestLog' (a nil value)
Debug:
   Carbonite.Quests\NxQuest.lua:5832: ShowUIPanel()
   Carbonite.Quests\NxQuest.lua:2902:
      Carbonite.Quests\NxQuest.lua:2899
   [C]: ShowUIPanel()
   Carbonite.Quests\NxQuest.lua:2852: ToggleQuestLog()
   [string "TOGGLEQUESTLOG"]:1:
      [string "TOGGLEQUESTLOG"]:1
Locals:
self = <table> {
 IconTracking = <table> {
 }
 UnpackCategory = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:10283
 DailyTypes = <table> {
 }
 IsTargeted = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:10049
 Menu_OnTrack = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:3227
 GetQuestReward = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:3280
 DecodeComRcv = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:10919
 MsgNotInDB = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:5205
 Watch = <table> {
 }
 PartyStartSend = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:11156
 SortQuests = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:4278
 NullQuest = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:11300
 CheckQuestSE = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:3165
 GetFromPlyr = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:5019
 Custom = <table> {
 }
 TTChange = <table> {
 }
 TooltipProcess2 = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:5314
 IdToCurQ = <table> {
 }
 PerColors = <table> {
 }
 GetClosestObjectivePos = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:10563
 RecordQuestsLog = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:3466
 ExtractTitle = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:4254
 CalcCNumMax = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:4074
 UnpackObjective = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:10321
 ClearCaptured = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:5039
 TooltipProcess = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:5290
 SelectBlizz = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:3334
 UnpackNext = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:10274
 ShowUIPanel = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:5817
 CapturePlyrData = <table> {
 }
 GetObjectiveType = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:10334
 PartyUpdateTimer = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:11149
 MapChanged = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:3971
 OnParty_members_changed = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:11015
 AlchemistsApprenticeData = <table> {
 }
 UpdateQuestDetails = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:8150
 DailyIds = <table> {
 }
 CalcDesc = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:4215
 QLocColors = <table> {
 }
 CalcPreviousDone = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:4117
 AccessAllQuests = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:3414
 IconOnMouseDown = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:8095
 UpdateGiverIconMenu = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:9944
 WatchAtLogin = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:4850
 CreateLink = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:4246
 LightHeadedAttach = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:5885
 RecordQuestAcceptOrFinish = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:4402
 Goto = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:4880
 InitQuestCharacter = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:2154
 RealQEntries = 38
 AcceptQuest = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:3260
 GetHistoryTimer = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:4167
 Requirements = <table> {
 }
 TellPartyOfChanges = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:4665
 Cols = <table> {
 }
 CreateGiverIconMenu = <function> defined @Interface\AddOn
AddOns:
  Swatter, v7.7.6000 (SwimmingSeadragon)
  Ailo, v
  AllTheThings, v1.6.4a
  AucAdvanced, v7.7.6000 (SwimmingSeadragon)
  AucFilterBasic, v7.7.6000 (SwimmingSeadragon)
  AucStatHistogram, v7.7.6000 (SwimmingSeadragon)
  AucStatiLevel, v7.7.6000 (SwimmingSeadragon)
  AucStatPurchased, v7.7.6000 (SwimmingSeadragon)
  AucStatSimple, v7.7.6000 (SwimmingSeadragon)
  AucStatStdDev, v7.7.6000 (SwimmingSeadragon)
  AucUtilFixAH, v7.7.6000 (SwimmingSeadragon)
  BeanCounter, v7.7.6000 (SwimmingSeadragon)
  BigWigs, vv100.2
  Carbonite, v8.0.0
  CarboniteQuests, v8.0.0
  Details, v
  DetailsDmgRank, v
  DetailsDpsTuning, v
  DetailsEncounterDetails, v
  DetailsRaidCheck, v
  DetailsRaidInfoEmeraldNightmare, v
  DetailsRaidInfoNighthold, v
  DetailsRaidInfoTombOfSargeras, v
  DetailsRaidInfoTrialOfValor, v
  DetailsStreamer, v
  DetailsTimeAttack, v
  DetailsTinyThreat, v
  DetailsVanguard, v
  ElvUI, v10.77
  Enchantrix, v7.7.6000 (SwimmingSeadragon)
  EnchantrixBarker, v7.7.6000 (SwimmingSeadragon)
  GoldBanker, v1.3
  GTFO, v4.46
  Incognito, v1.4.1
  Informant, v7.7.6000 (SwimmingSeadragon)
  PetBattleMaster, v7.0.4
  Postal, vv3.6.0
  ProspectBarLives, v3.3
  SilverDragon, vv4.0.9
  SilverDragonBattleForAzeroth, vv4.0.9
  SilverDragonBurningCrusade, vv4.0.9
  SilverDragonCataclysm, vv4.0.9
  SilverDragonLegion, vv4.0.9
  SilverDragonMists, vv4.0.9
  SilverDragonVanilla, vv4.0.9
  SilverDragonWarlords, vv4.0.9
  SilverDragonWrath, vv4.0.9
  SlideBar, v7.7.6000 (SwimmingSeadragon)
  Stubby, v7.7.6000 (SwimmingSeadragon)
  Titan, v5.14.0.80000
  TitanBag, v5.14.0.80000
  TitanClock, v5.14.0.80000
  TitanGold, v5.14.0.80000
  TitanLocation, v5.14.0.80000
  TitanLootType, v5.14.0.80000
  TitanPerformance, v5.14.0.80000
  TitanRepair, v5.14.0.80000
  TitanVolume, v5.14.0.80000
  TitanXP, v5.14.0.80000
  WoWDBProfiler, v
  BlizRuntimeLib_enUS v8.0.1.80000 <none>
  (ck=759)

**Comment by SteveEbey73742** [comment]
I did test with all addons off, but I captured the lua error before I did the test.

**Comment by IrcDirk** [comment]
First of all update... many fixes in one day. On my side all works ok... weird.

**Comment by SteveEbey73742** [comment]
tested on both of our computers, windows 10 and I also tested on my linux install, same result.  made a fresh fork, will look and see what I can find.

**Comment by IrcDirk** [comment]
Update and check again now. I did rewriten those functions and tested in both ways now it should be OK.

**Comment by SteveEbey73742** [comment]
Works as expected. Thank you for your work on this. Please know that I appreciate all that you and everyone else do to bring the game this wonderful tool.  My daughter has started playing wow and we will be using this to aid here questing.  She is high functioning autistic, and we hope the game helps in brain development and improvement in eye hand coordination.
