### ISSUE TITLE
After installing version 104 of Carbonite Maps I started getting the following

### ISSUE THREAD

**Issue by jerryjoh** [mikepauer/Carbonite.Quests#44]
2x ...lizzard_MapCanvas\MapCanvas_ScrollContainerMixin.lua:428: attempt to index local 'layers' (a nil value)
...lizzard_MapCanvas\MapCanvas_ScrollContainerMixin.lua:428: in function `CreateZoomLevels'
...lizzard_MapCanvas\MapCanvas_ScrollContainerMixin.lua:415: in function `OnCanvasSizeChanged'
...lizzard_MapCanvas\MapCanvas_ScrollContainerMixin.lua:407: in function `SetMapID'
...aceBlizzard_MapCanvas\Blizzard_MapCanvas.lua:33: in function `SetMapID'
**Carbonite.Quests\NxQuest.lua**:11621: in function `?'
...bot\Libs\CallbackHandler-1.0\CallbackHandler-1.0-7.lua:145: in function <...bot\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:145>
[string "safecall Dispatcher[1]"]:4: in function <[string "safecall Dispatcher[1]"]:4>
[C]: ?
[string "safecall Dispatcher[1]"]:13: in function `?'
...bot\Libs\CallbackHandler-1.0\CallbackHandler-1.0-7.lua:90: in function `Fire'
AskMrRobot\Libs\AceEvent-3.0\AceEvent-3.0-4.lua:120: in function <AskMrRobot\Libs\AceEvent-3.0\AceEvent-3.0.lua:119>

**Comment by IrcDirk** [comment]
It might be incompatiblity with AskMrRobot, disable all addons except Carbonite + this module and check again.

**Comment by jerryjoh** [comment]
Something you changed (or that was updated by askmrrobot) fixed this issue. Thanks!
