### ISSUE TITLE
NxQuest.lua:11518: attempt to index local 'color' (a nil value)

### ISSUE THREAD

**Issue by Thrumbar** [mikepauer/Carbonite.Quests#45]
Got this upon compleating WQ in Darkshore....

102x Carbonite.Quests\NxQuest.lua:11518: attempt to index local 'color' (a nil value)
Carbonite.Quests\NxQuest.lua:11518: in function `GenWQTip'
Carbonite.Quests\NxQuest.lua:11624: in function `UpdateDB'
Carbonite.Quests\NxQuest.lua:11636: in function <Carbonite.Quests\NxQuest.lua:11636>

Locals:
self = <table> {
 UpdateDB = <function> defined @Carbonite.Quests\NxQuest.lua:11585
 Win = <table> {
 }
 RegisterMessage = <function> defined @DataStore\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:90
 UnregisterMessage = <function> defined @DataStore\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:153
 Update = <function> defined @Carbonite.Quests\NxQuest.lua:11652
 List = <table> {
 }
 SendMessage = <function> defined @DataStore\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:59
 ButMenu = <table> {
 }
 GenWQTip = <function> defined @Carbonite.Quests\NxQuest.lua:11442
 UnregisterAllEvents = <function> defined @DataStore\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:174
 RegisterEvent = <function> defined @DataStore\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:90
 UnregisterAllMessages = <function> defined @DataStore\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:174
 Open = <function> defined @Carbonite.Quests\NxQuest.lua:11336
 UnregisterEvent = <function> defined @DataStore\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:153
 OnListEvent = <function> defined @Carbonite.Quests\NxQuest.lua:11575
 FlashColor = 0
 Menu = <table> {
 }
 FirstUpdate = true
 WinUpdateFade = <function> defined @Carbonite.Quests\NxQuest.lua:11436
 CheckBounty = <function> defined @Carbonite.Quests\NxQuest.lua:11641
 GetWQReward = <function> defined @Carbonite.Quests\NxQuest.lua:11536
 Opened = true
}
questId = 44932
title = "The Nighthold: Ettin Your Foot In The Door"
factionID = 1859
capped = false
tagID = 141
tagName = "Raid World Quest"
worldQuestType = 8
rarity = 1
isElite = true
tradeskillLineIndex = nil
displayTimeLeft = true
color = <table> {
 hex = "|cffffffff"
 r = 1
 color = <table> {
 }
 g = 1
 b = 1
}
style = <table> {
 headerText = "Rewards"
 headerColor = <table> {
 }
 wrapHeaderText = true
 postHeaderBlankLineCount = 0
 prefixBlankLineCount = 1
}
tipdone = false
percent = nil
xp = 0
artifactXP = 0
numAddedQuestCurrencies = 0
honorAmount = 0
money = 0
numQuestRewards = 1
name = "Shard of Compacted Energy"
icon = 840008
numItems = 1
quality = 0
_ = true
itemID = 141932
color = nil
(*temporary) = <function> defined =[C]:-1
(*temporary) = WQListTip {
 0 = <userdata>
 updateTooltip = 0.2
 needsReset = true
 BottomOverlay = <unnamed> {
 }
 TopOverlay = <unnamed> {
 }
}
(*temporary) = "|T840008:0|t Shard of Compacted Energy"
(*temporary) = "840008"
(*temporary) = ":0|t "
(*temporary) = ""
(*temporary) = "Shard of Compacted Energy"
(*temporary) = "attempt to index local 'color' (a nil value)"
worldquestdb = <table> {
 43427 = <table> {
 }
 44122 = <table> {
 }
 44187 = <table> {
 }
 42112 = <table> {
 }
 41427 = <table> {
 }
 44894 = <table> {
 }
 41057 = <table> {
 }
 41311 = <table> {
 }
 43772 = <table> {
 }
 41687 = <table> {
 }
 41926 = <table> {
 }
 46111 = <table> {
 }
 42151 = <table> {
 }
 41701 = <table> {
 }
 42274 = <table> {
 }
 42150 = <table> {
 }
 45973 = <table> {
 }
 41930 = <table> {
 }
 45473 = <table> {
 }
 43985 = <table> {
 }
 44932 = <table> {
 }
 45977 = <table> {
 }
 46707 = <table> {
 }
 44812 = <table> {
 }
 41493 = <table> {
 }
 42024 = <table> {
 }
 43432 = <table> {
 }
 42174 = <table> {
 }
 41861 = <table> {
 }
 43753 = <table> {
 }
 43327 = <table> {
 }
 42119 = <table> {
 }
 41428 = <table> {
 }
 44895 = <table> {
 }
 43183 = <table> {
 }
 43324 = <table> {
 }
 45878 = <table> {
 }
 43454 = <table> {
 }
 41944 = <table> {
 }
 43710 = <table> {
 }
 43599 = <table> {
 }
 41257 = <table> {
 }
 46236 = <table> {
 }
 44033 = <table> {
 }
 43027 = <table> {
 }
 42714 = <table> {
 }
 42086 = <table> {
 }
 42025 = <table> {
 }
 42712 = <table> {
 }
 41273 = <table> {
 }
 44299 = <table> {
 }
 46933 = <table> {
 }
 44744 = <table> {
 }
 42160 = <table> {
 }
 42004 = <table> {
 }
 41482 = <table> {
 }
}
worldquesttip = WQListTip {
 0 = <userdata>

**Comment by Palonblade** [comment]
I get this at login on every toon so far
