### ISSUE TITLE
Completing quest step causes system to pause for a moment

### ISSUE THREAD

**Issue by BomSquad** [mikepauer/Carbonite.Quests#47]
When questing as soon as a quest step is completed by anyone in the party (i.e., killed a quest mob, collected quest resource, etc) the entire game appears to pause for a moment. It feels like about .25 seconds of a pause and then everything goes back to normal until the next quest step is completed.
Disabling Carbonite.Quests stops this from occurring. 
I have LUA errors turned on but I am getting no errors.

**Comment by Thrumbar** [comment]
Sound like related to this https://github.com/mikepauer/Carbonite/issues/61...

**Comment by BomSquad** [comment]
After reading https://github.com/mikepauer/Carbonite/issues/61 I would have to agree that it sounds exactly like the issue I am experiencing.

**Comment by IrcDirk** [comment]
Ok, try again now, it should be better now.
