### ISSUE TITLE
0,5-0,6 seconds lagspikes after Zuldazar wq killing Xolotal

### ISSUE THREAD

**Issue by Swirrel** [mikepauer/Carbonite.Quests#48]
I had 3 wq's to go for Wide World of Quests and needed 3 more wq's for Zuldazar rep faction, so I flew from Zo'bal Ruins (Nazmir), to Atal'dazer (where I did a pet battle wq) (that's 3-1 = 2). From Atal'dazar flightpoint to Warport Rastari flightpoint where I killed Xolotal for another wq (2-1 = 1). From there I ran in travel form to Xibala flightpoint and did a wq (1-1 = 0) - here I should have gotten my Wide World of Quests achievement, but didn't. The achivement tracker and the achievement journal still says 99/100 as it did when I was missing 1 wq.
Instead I got lagspikes every 0,5-0,6 seconds (about every 2 steps my character takes when running). I even did a wq at the shore near Xibala fp for Tortollan Seekers, to make sure I hit 100 cus the Achievement Journal said 99/100 still. I didn't fix the lagspikes and I still didn't get the achivement.
I hearthstoned back to The Great Seal in Zuldazar with these strange lagspikes.

Doing a reload did nothing to fix it.
Doing a relog did nothing to fix it.
Exiting them game and logging back in did nothing.

Then I turned Carbonite Maps off and reloaded - that fixed the lagspikes.
Then I turned Carbonite Maps on again and reloaded - Lagspikes are back.
Then I turned Carbonite Quests off and reloaded - lagspikes vanished.

I haven't turned Carbonite Quests on again, as those strange lagspikes makes me feel like I have seasickness and want to vomit. It feel nausiated.
Carbonite have been working fine otherwise the past many days. It wasn't until after I'd killed Xolotal where the achievement didn't "click" that the lagspikes started.

I have no errors to show you I'm afraid.

**Comment by Swirrel** [comment]
As it was fairly late for me when I posted my issue, I didn't have the brainpower to get the Clone or Download => Download Zip for both Carb Map or Carb Quest from github. I have done that now though.
Getting the newest version of Carb Map and Quests, I don't know if it makes a difference to my sudden issue, so I have taken a copy of my old configuration before updating anything.. you for know, for those "just in case" moments.
(I take a copy of my wow cache, interface, wtf and screenshots folder about once a month, as I'd rather be safe, than sorry)

On a side note:
Also it seems that the Twitch Client wants to decide whether or not my Carb addons should be set for Release or Alpha, so like 10 minutes ago I checked if all of Carb was still set to Alpha which I noticed they wasn't, so I've changed them all to Alpha once again.

**Comment by Swirrel** [comment]
Updating both Carb Map and Quest from this site have done nothing to ease the lagspikes on my druid, so on him I've got Carbonite quests turned off.
I did want to test if it was just my druid I had the issue on, so I logged on to my lvl 113 hunter with carbonite quests on and on her I don't have the lagspikes, but she also can't do wq's yet.

**Comment by Swirrel** [comment]
So because I'm an idiot and didn't have enough brainpower left late last night, and had to reboot my brain this morning, it dawned on me that the achievement for a Wide World of Quests says a 100 "different" world quests, I just did a cooking wq in Sxaletradeer Post in Zuldazar for the rank 3 recipe of Lane Snapper. After I handed it in I got the Wide World of Quests achievement... So I thought... hey... I'll try turning on Carbonite Quest again and see if I still get lagspikes.
Carb Quest are running and functioning without a hitch. No Lagspikes.

I'll leave the issue here, incase it's anything you'd want to look into though no guarentees it does have anything to do with Carbonite Quest, but if it does, the info might be enough to go back and look into for the future.
I'll leave it up to you on whether or not to close this issue.


//Jag.

**Comment by IrcDirk** [comment]
Thats weird! It might be a Blizz bug raleted to event... didnt happened to me but ill monitor this.

**Comment by Swirrel** [comment]
Thank you.

**Comment by Swirrel** [comment]
Hi.

So this is happening again. It started a day or so after there was the last Release (not alpha release) for Carbonite Maps, though if I turn Carbonite Quest of it stops. Turning Carbonite Quests on again make the very subtle lagspikes come back.

Rolling back Carb Map to the last alpha doesn't change anything, but it also doesn't make the spikes worse.
Rolling back Carb Quests make the spikes slightly more pronounced.
Turning Carbonite Quests off make the lag spikes go away entirely.

What is even more strange still, it's only an issue on my Druid and it's more visible when he's in form (bear form, cat form, travel form). I do not have the issue on either my lvl 120 Mage and 120 Hunter which also have World Quests unlocked. (Rogue, Shaman and DK is still between 110 and 120)

I would say this though, for the past couple of days when I log in to WoW on either Mage, Hunter or Druid, I get a sound notification from Carbonite that is accepting a quest but nothing shows in the chat which is weird. It's only been happening for the past 2-3 days though.
It's not a WoW sound, and the only addon that I have that makes any sort of sounds is Carbonite Maps/Quests.
Also it's worth mentioning that it only happens the very first time on each of those 3 toons when I come online that day. Right now I've exited the game 4 times and logged in 3 times since I originally came online around 9pm server time.
I've no idea what it is that Carbonite is accepting.
Now that I think about it, that started at the same time as I got those strange lag spikes back... I wonder if there is a connection?

As always, thank you for your time spent trying to figure this out and for the help you provide.

//Jag.

**Comment by Swirrel** [comment]
So logging directly in to my hunter (yesterday thursday) made none of the above happen. I've also had my shaman, mage, and druid logged and still nothing. It's annoying that I can't reproduce the issue and that it seems random.
That doesn't tell you much though. Sorry.

**Comment by Swirrel** [comment]
As I am (now was) tracking a few achievements on Jag I decided to turn of the last 3, 2, 1 I had set to be tracked (3 Ritualist Who?, 2 You Said Crossing the Streams Was Bad, 1 Jungle Stalker).. That's the reverse order I set them to track on, so I started with turning off nr 3 which made a slight difference, then I turned of nr 2 which also made a slight difference, so I turned of nr 1 and now I can't see any lagspikes on Jag whether he's running or walking in Travel form (I normally use Travel Form when I run around from location to location doing wq's)...
Anyway, the point with me explaining this, is that I turned of 3 of the 6 achievements I had tracking (I still have Insane in the Membrane, Life Finds a Way... To Die!, Sabertron Assemble tracking on the quest tracker) Insane have been there for a few years (before legion), and the other 2 I added like a week after Jag turned 120 which was august 18th 2018.

I can't imagine that it would make a difference but Jag is a Tauren, his tmog is the Nordrassil Raiment from Serpentshrine Cavern in TBC and his weapon is tmogged in to Avatar of Ursoc (Blue). But again, he's used that for a very long while... some time in Legion..

I'll keep posting here in case I remember/try anything else.

**Comment by Swirrel** [comment]
This I did before I turned tracked achievement off.
With in Carbonite  > Quest Module > Quest Options: I've turned of Show Daily Quest Count, Share Quest Progress
![image](https://user-images.githubusercontent.com/31900265/47954937-f431f700-df90-11e8-9a12-a0d09ce20110.png)
![image](https://user-images.githubusercontent.com/31900265/47954941-014ee600-df91-11e8-995a-38fbde891424.png)
The screenies is merely so you can see what is always otherwise turned on. Changing those 2 things from on to off didn't require a reload, but I did a reload anyway.

**Comment by Swirrel** [comment]
Also, Carbonite Maps swings alot in it's MB usage. It goes from 23.xx MB rising around 2,5 to 3MB up to or over 50MB and then goes instantly back to 23.xx MB rising steadly again up to 50+ MB over and over and over again... It doesn't matter what I'm doing or not doing, which toon I'm on or where I am (right now I'm in norther Vol'dun), but it's the same if I'm on my lvl 110 shaman in his Garrison or if I on my mage flying a guildie around from Old Dalaran to Stormpeaks.
I would say this though, Friday last week I was raiding and had no issues with lag... I seem to have zero issues with any form of lag in either dungeons or raids no matter their difficulty no matter their expansion or in Vanilla.
![image](https://user-images.githubusercontent.com/31900265/47955014-fa74a300-df91-11e8-8432-949702ddf362.png)

**Comment by Swirrel** [comment]
And no strange lag either when I use a flight master flying from northern Vol'dun to Vulpera Hideaway

**Comment by IrcDirk** [comment]
So if i did get it right tracking Achivements does the lag? Turning this off made lag go away?

**Comment by IrcDirk** [comment]
Ok, got the same lags with achiv "Wide World of Quests". I think i solved it. I will commit this fix soon. Need to test a little more.

**Comment by Swirrel** [comment]
Admittedly I haven't turned on the before mentioned achievements on Jag because he's been lag free since I turned them off and as he's my main and I play on him a lot, I don't fancy lag spikes no matter their size.
I would said this though, that the achievements I'm still tracking on him haven't caused any lag either.

**Comment by Swirrel** [comment]
> 
> 
> So if i did get it right tracking Achivements does the lag? Turning this off made lag go away?

You got it right.

**Comment by IrcDirk** [comment]
Fixed tested should not accour again.

**Comment by Swirrel** [comment]
Thank you :)
