### ISSUE TITLE
Legion Emissaries at Quest Tracker - option to disable/remove is missing

### ISSUE THREAD

**Issue by Swirrel** [mikepauer/Carbonite.Quests#49]
I've left a comment here: http://www.wowinterface.com/forums/showthread.php?t=56632
Yet you've told me to post my issues here, so that I'll do.

This "thing" about having Legion Emissaries on the Quest Tracker window is about the worst idea ever implemented into Carbonite Quest, and I've used Carbonite for around a decade. To say that I'm less than pleased, is an understatement. I don't want Legion Emissaries on my Quest Tracker and I don't need Legion Emissaries on my Quest Tracker.
If I want to do my Legion Emissaries, I'll go to Legion to do them, but I do not want to have to stare at them every second of every day.
If they HAVE to be there, at least implement the option to turn it off.

Until that becomes a reality, tell me which download I need to chose to roll back 1 version of Carbonite Quests.

/Jag.

![image](https://user-images.githubusercontent.com/31900265/44994717-3b573800-afa0-11e8-8dff-4fe71aa12990.png)
The questtracker is on the right hand side.

**Comment by IrcDirk** [comment]
It sounds very ungratefully... U dont have to use it.

Its implemented in Alpha versions and they are for testing purposes. Of course there will be option to disable this but that will be implemented in the future. You have to wait....

**Comment by Swirrel** [comment]
It's not that I'm ungrateful for all of Carbonite. Not at all. But that Emissary thing... you got the gist of.

So if I close the game, and set Carb Quest for Release, will it "roll it back, so I don't seem them?

**Comment by Swirrel** [comment]
Besides that, it appear to be working fine. I don't have errors or bugs popping up. I'll go do my BfA Emissary to see if that works as I believe it's suppose to.

**Comment by Swirrel** [comment]
Running around in travel form in Dazar'alor in Zuldazar (Horde main city), I now have some mellow lagspikes, but they are noticeable. Turning Carb Quests off, return the running to normal with no lagspikes. Turning Carb Quests on again, makes them reappear.
Logging on to my lvl 113 hunter also stationed in Dazar'alor in Zuldazar she has no lagspikes, absolutely none and on her, she's only seeing the Legion Emissaries.

**Comment by Swirrel** [comment]
Rolling back to a release version of Carbonite Quests from 30/8-18 have fixed the sudden mellow lagspikes.

**Comment by IrcDirk** [comment]
Lag lagspikes should be off with latest commit.

**Comment by Swirrel** [comment]
That is indeed much appreciated. However, I think I'll wait for when I can turn the stuff off :) Sorry.
I mean, what I have now works. I've fiddled alot with Carbonite today. I learn something every time and forge it until the next time, hehe.

And I am sorry, that my original post sounded ungrateful. I know it still does as I haven't changed it. But I hope that you can forgive my lack of respect.

**Comment by IrcDirk** [comment]
No problem, just remember we are all humans and all have own lifes ;)
