### ISSUE TITLE
World Quest group finder

### ISSUE THREAD

**Issue by Cherioz** [mikepauer/Carbonite.Quests#5]
No interaction between quest watch list and WQGF , no option to click or right click to find groups or relaunch WQGF addon to look for world quests  group..   Blizzard default quest watch list is only way now and is always up on my screen while questing , which defies the idea of having a Carbonite quest addon :/  not fully but for a good part

**Comment by fdellwing** [comment]
I use the "middle mouse button" click method from WQGF. Just open BlizzMap with Alt+M und click the quest you want to search with your mousewheel.

It is not optimal, but it works perfectly fine.

Would be nice to get this interaction on CarbMap as well, but could be a bit hard?

**Comment by mikepauer** [comment]
It wouldn't be hard, but it should be the other way around, that WQGF adds support for Carb if they feel it's worthwhile, and not that Carb supports it.. there are just too many mapping and quest helping addons for us to be making code modifications to add checks for each one and special routines for them

**Comment by IrcDirk** [comment]
I totally agree with @mikepauer
