### ISSUE TITLE
Carb Questlog states that I have 2/25 quests, but questlog is empty

### ISSUE THREAD

**Issue by Swirrel** [mikepauer/Carbonite.Quests#51]
Hi.

So as the Subject says, Carb Questlog states that I have 2/25 quests in my questlog but I don't have any quests in my questlog. Also opening the Blizzard map and their quest window shows I have zero quests.
It's been like that for a while, but I honestly can't say how long a while.

I'm submitting a few screenies, so you can see what I'm talking about.
![wowscrnshot_101218_171824](https://user-images.githubusercontent.com/31900265/46878348-59d40d00-ce43-11e8-9987-6a40cadfd2dc.jpg)
![wowscrnshot_101218_171838](https://user-images.githubusercontent.com/31900265/46878349-59d40d00-ce43-11e8-8b08-ad7f1ff7f2a5.jpg)

Thank You :)

**Comment by IrcDirk** [comment]
There are 2 weekly Quest for PVP that are hidden, there was somewhere topic or issue about this. I need to update this not to add those in count of active quests.

**Comment by Swirrel** [comment]
Awesome.

It's just nice to know that there is a reason and that it's not some strange bug.
