### ISSUE TITLE
Quests tossing endless Errors bfa 8.1 day one 

### ISSUE THREAD

**Issue by reflexwolf** [mikepauer/Carbonite.Quests#56]
I'm getting a lot of errors and its slowing down my system quite a bit, quests looks like they are working just keep tossing off this error endlessly.

I have also tested it with just Maps and Quests up and it keeps doing the rapped number of errors, the 2919 in the took less than a minute to add up. 

2919x Carbonite.Quests\NxQuest.lua:8112: attempt to call global 'WorldMap_SetupWorldQuestButton' (a nil value)
Carbonite.Quests\NxQuest.lua:8112: in function `UpdateIcons'
Carbonite\NxMap.lua:4940: in function `Update'
Carbonite\NxMap.lua:3878: in function <Carbonite\NxMap.lua:3762>

Locals:
self = <table> {
 IconTracking = <table> {
 }
 UnpackCategory = <function> defined @Carbonite.Quests\NxQuest.lua:10488
 DailyTypes = <table> {
 }
 IsTargeted = <function> defined @Carbonite.Quests\NxQuest.lua:10254
 Menu_OnTrack = <function> defined @Carbonite.Quests\NxQuest.lua:3268
 GetQuestReward = <function> defined @Carbonite.Quests\NxQuest.lua:3322
 DecodeComRcv = <function> defined @Carbonite.Quests\NxQuest.lua:11124
 MsgNotInDB = <function> defined @Carbonite.Quests\NxQuest.lua:5254
 Watch = <table> {
 }
 PartyStartSend = <function> defined @Carbonite.Quests\NxQuest.lua:11378
 SortQuests = <function> defined @Carbonite.Quests\NxQuest.lua:4329
 NullQuest = <function> defined @Carbonite.Quests\NxQuest.lua:11522
 CheckQuestSE = <function> defined @Carbonite.Quests\NxQuest.lua:3206
 GetFromPlyr = <function> defined @Carbonite.Quests\NxQuest.lua:5068
 Custom = <table> {
 }
 TTChange = <table> {
 }
 TooltipProcess2 = <function> defined @Carbonite.Quests\NxQuest.lua:5363
 IdToCurQ = <table> {
 }
 PerColors = <table> {
 }
 GetClosestObjectivePos = <function> defined @Carbonite.Quests\NxQuest.lua:10768
 RecordQuestsLog = <function> defined @Carbonite.Quests\NxQuest.lua:3508
 ExtractTitle = <function> defined @Carbonite.Quests\NxQuest.lua:4305
 CalcCNumMax = <function> defined @Carbonite.Quests\NxQuest.lua:4125
 UnpackObjective = <function> defined @Carbonite.Quests\NxQuest.lua:10526
 ClearCaptured = <function> defined @Carbonite.Quests\NxQuest.lua:5088
 TooltipProcess = <function> defined @Carbonite.Quests\NxQuest.lua:5339
 SelectBlizz = <function> defined @Carbonite.Quests\NxQuest.lua:3376
 UnpackNext = <function> defined @Carbonite.Quests\NxQuest.lua:10479
 ShowUIPanel = <function> defined @Carbonite.Quests\NxQuest.lua:5866
 CapturePlyrData = <table> {
 }
 GetObjectiveType = <function> defined @Carbonite.Quests\NxQuest.lua:10539
 PartyUpdateTimer = <function> defined @Carbonite.Quests\NxQuest.lua:11371
 MapChanged = <function> defined @Carbonite.Quests\NxQuest.lua:4017
 OnParty_members_changed = <function> defined @Carbonite.Quests\NxQuest.lua:11220
 AlchemistsApprenticeData = <table> {
 }
 UpdateQuestDetails = <function> defined @Carbonite.Quests\NxQuest.lua:8229
 DailyIds = <table> {
 }
 CalcDesc = <function> defined @Carbonite.Quests\NxQuest.lua:4266
 QLocColors = <table> {
 }
 CalcPreviousDone = <function> defined @Carbonite.Quests\NxQuest.lua:4168
 AccessAllQuests = <function> defined @Carbonite.Quests\NxQuest.lua:3456
 IconOnMouseDown = <function> defined @Carbonite.Quests\NxQuest.lua:8174
 UpdateGiverIconMenu = <function> defined @Carbonite.Quests\NxQuest.lua:10149
 WatchAtLogin = <function> defined @Carbonite.Quests\NxQuest.lua:4899
 CreateLink = <function> defined @Carbonite.Quests\NxQuest.lua:4297
 LightHeadedAttach = <function> defined @Carbonite.Quests\NxQuest.lua:5934
 RecordQuestAcceptOrFinish = <function> defined @Carbonite.Quests\NxQuest.lua:4451
 Goto = <function> defined @Carbonite.Quests\NxQuest.lua:4929
 InitQuestCharacter = <function> defined @Carbonite.Quests\NxQuest.lua:2172
 RealQEntries = 37
 AcceptQuest = <function> defined @Carbonite.Quests\NxQuest.lua:3302
 GetHistoryTimer = <function> defined @Carbonite.Quests\NxQuest.lua:4218
 Requirements = <table> {
 }
 TellPartyOfChanges = <function> defined @Carbonite.Quests\NxQuest.lua:4714
 Cols = <table> {
 }
 CreateGiverIconMenu = <function> defined @AddO

**Comment by Thrumbar** [comment]
Pull awaiting that should fix that..

**Comment by reflexwolf** [comment]
thank you! I figured it was in the works but a heads up cant hurt.

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=icon>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=link>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>
