### ISSUE TITLE
Carbonite Quest Tracker set to show quests upon being accepted, but rarely ever does (atleast not for anything related to BfA)

### ISSUE THREAD

**Issue by Swirrel** [mikepauer/Carbonite.Quests#59]
Hi.

Pretty much since the release of BfA any quest accepted from a questgiver isn't popping up on the Carbonite Quest Tracker and has to be manually turned on to show it, though the settings are set to do this automatically.
I've noticed this for about 99% of all quests (not world quests) since the release of BfA and on 6 different characters. I can't say if it's because I play on a High pop server (draenor horde) or if it's something else.. it also doesn't give of any errors or other bugs as a response for them not being shown.
The same thing, for me, also happend in the earlier days of Legion, but was either fixed by association to something else, or just suddenly started working properly.
Alas, this doesn't appear to be an issue with any quests from the WoD expansion or before WoD or any event quests, like the dailies that you can pick up in your Garrison currently belonging to the Winter Veil Event (this time of year). Also the "You're a Mean One..." daily from an Npc in Orgrimmar also for the Winter Veil Event.. 
Accepting those quests shows instantly on the Quest Tracker.

Thank you.

**Comment by IrcDirk** [comment]
Any one else can confirm this issue?

**Comment by Thrumbar** [comment]
I to have the said issue.  Tried it with only Carbonite active and all the quest in BfA were watched but when I turned on the other addons it did not.  This may be addon interference with addons that are quest related..  I also turned off the option that blocks Blizzards auto track..

**Comment by Swirrel** [comment]
I'll try that the next time I come online. It's just wierd cus the first addon I've added in BfA was around a month ago named SellJunk because I didn't like a change in ElvUI which I ofc disabled, so it wouldn't conflict with SellJunk.
The second addon I've added is tdBattlePetScript and tdBattlePetScript_Rematch but those I added on January 4th (2 days ago) because I sorely need to learn to create tdScripts for my Pet Battle strategies uploaded on www.wow-petguide.com
The third newest addon I've added is BuyEmAll, but that was added in late Legion.

![image](https://user-images.githubusercontent.com/31900265/50736482-796a9f80-11be-11e9-9459-67df9bdf4014.png)
That's a picture of all my addons. The only addon there's been an update too for me today was Elvui, but that's through it's own Client.

If this is another addons fault, the only of the one, maybe two I have that could be a culprit: AdvancedInterfaceOptions or AIO for short due to the enormity of changes it can bring to the game... it basically utilizes what is still in wow but isn't shown by blizzard. What I use it for is to tell me Enter Combat and Leaving Combat along with Scrolling Combat Text. I added it in early Legion when Blizzard removed the visual appearence of Enter-/Leaving Combat and Scrolling Combat Text. But again, it can do so much else.

If it's not AIO, then there's a possibility it might be Chinchilla. Chinchilla is for all intent and purposes a minimap, but it can do so much more than just that. Would be strange though, as I have like 95% of all it can do, turned off, cus I just need a moveable minimap that would use very little memory, easy to set-up and that was updated by it's developer and Chinchilla has all of that. I don't even remember when I added Chinchilla to my addons, it's been years. Ofc when Carbonite also became a minimap I disabled that part of Carbonite, again to avoid conflict between the minimap I wanted and the minimap that came with Carbonite.

Thank you.

**Comment by Swirrel** [comment]
With a little luck I might have time next week to "mess" around with this.
The beginning of January have just been stupidly busy, I've barely had time to be online.

**Comment by Swirrel** [comment]
It's not Chinchilla Minimap as it's QuestTracker is turned off 
![image](https://user-images.githubusercontent.com/31900265/51341359-72327400-1a91-11e9-8c52-906bf4e6a344.png)
Also, I've used that addon for ages and it's questtracker have always been off.

**Comment by IrcDirk** [comment]
Disable addons one by one. Turning off some options doesnt mean that some other function isnt messing around.
