### ISSUE TITLE
Carbonite Quest Bug in the middle of a pet battle that isn't a quest

### ISSUE THREAD

**Issue by Swirrel** [mikepauer/Carbonite.Quests#60]
12x Carbonite.Quests\NxQuest.lua:11889: attempt to compare number with nil
Carbonite.Quests\NxQuest.lua:11889: in function `Update'
Carbonite.Quests\NxQuest.lua:6946: in function `LogUpdate'
Carbonite.Quests\NxQuest.lua:6733: in function `func'
Carbonite.Quests\NxQuest.lua:6749: in function `Refresh'
Carbonite.Quests\NxQuest.lua:6817: in function `?'
...oot\Libs\CallbackHandler-1.0\CallbackHandler-1.0-7.lua:119: in function <...oot\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:119>
[C]: ?
...oot\Libs\CallbackHandler-1.0\CallbackHandler-1.0-7.lua:29: in function <...oot\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:25>
...oot\Libs\CallbackHandler-1.0\CallbackHandler-1.0-7.lua:64: in function `Fire'
Carbonite\Libs\AceEvent-3.0\AceEvent-3.0-4.lua:120: in function <Carbonite\Libs\AceEvent-3.0\AceEvent-3.0.lua:119>

![image](https://user-images.githubusercontent.com/31900265/50371679-065b0980-05c0-11e9-954d-08a59f6ddea5.png)

Notice the message from System in the left chat (lower left) - which is so strange as that's the only Bug I've gotten since I last reported yesterday on this site.

**Comment by Swirrel** [comment]
Update.

So after finishing Aquatic pets vs. Small Beginnings (which is where I am atm, (making progress in doing Family Battler), I noticed after completing the actual thing in the 3rd try that the Master Tamer I was up against have appear now as a pet battle world quest
![image](https://user-images.githubusercontent.com/31900265/50371819-55a23980-05c2-11e9-8b30-8eccd532a000.png)

**Comment by IrcDirk** [comment]
Allready fixed.

**Comment by Swirrel** [comment]
I didn't exprience the issue yesterday because I only had a few Master Tamers left to defeat, and none of those popped up as a world quest and the few I did alrdy was a world quest and had like 6hrs left on them.

However.. I'll see what I can do when I do pet battles at a more decent hour instead of 8am server time, in the morning

Thank you for applying a fix so fast, especially here at christmas time.
