### ISSUE TITLE
Possible issue or conflict with accountant?

### ISSUE THREAD

**Issue by radicaled06** [mikepauer/Carbonite.Quests#61]
Since the updates recently, I've been having an issue with turning in quests. I can click through the dialogue just fine, but when I'm clicking on 'Complete Quest' it has no function. No matter how many times I click, or how long I wait I cannot turn in my quests. I've tried re-logging, and reloading UI. It still persists. When I disable Carbonite Quests it allows me to turn in my quests again.

I pulled the below error from bugsack, but I don't know if it is directly related to the issue.

418x Carbonite.Quests\NxQuest.lua:11889: attempt to compare number with nil
Carbonite.Quests\NxQuest.lua:11889: in function `Update'
Carbonite.Quests\NxQuest.lua:6946: in function `LogUpdate'
Carbonite.Quests\NxQuest.lua:6733: in function `func'
Carbonite.Quests\NxQuest.lua:6749: in function `Refresh'
Carbonite.Quests\NxQuest.lua:6817: in function `?'
...sic\Libs\CallbackHandler-1.0\CallbackHandler-1.0-7.lua:119: in function <...sic\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:119>
[C]: ?
...sic\Libs\CallbackHandler-1.0\CallbackHandler-1.0-7.lua:29: in function <...sic\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:25>
...sic\Libs\CallbackHandler-1.0\CallbackHandler-1.0-7.lua:64: in function `Fire'
...ccountant_Classic\Libs\AceEvent-3.0\AceEvent-3.0-4.lua:120: in function <...ccountant_Classic\Libs\AceEvent-3.0\AceEvent-3.0.lua:119>

**Comment by IrcDirk** [comment]
Update to latest alpha.
