### ISSUE TITLE
Usage: local minutesLeft = C_TaskQuest.GetQuestTimeLeftMinutes(questID)

### ISSUE THREAD

**Issue by Thrumbar** [mikepauer/Carbonite.Quests#62]
3x FrameXML\WorldMapFrame.lua:116: Usage: local minutesLeft = C_TaskQuest.GetQuestTimeLeftMinutes(questID)
[C]: in function `GetQuestTimeLeftMinutes'
FrameXML\WorldMapFrame.lua:116: in function `WorldMap_AddQuestTimeToTooltip'
Carbonite.Quests\NxQuest.lua:11697: in function `GenWQTip'
Carbonite.Quests\NxQuest.lua:11842: in function `?'
...ack\Libs\CallbackHandler-1.0\CallbackHandler-1.0-7.lua:119: in function <...ack\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:119>
[C]: ?
...ack\Libs\CallbackHandler-1.0\CallbackHandler-1.0-7.lua:29: in function <...ack\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:25>
...ack\Libs\CallbackHandler-1.0\CallbackHandler-1.0-7.lua:64: in function `Fire'
Carbonite\Libs\AceEvent-3.0\AceEvent-3.0-4.lua:120: in function <Carbonite\Libs\AceEvent-3.0\AceEvent-3.0.lua:119>

**Comment by IrcDirk** [comment]
Cant reproduce...

**Comment by Thrumbar** [comment]
Sorry was testing some code I forgot about after I noticed that Blizzard is stopping use of displayTimeLeft arg in GetQuestTagInfo(questID)

      local tagID, tagName, worldQuestType, rarity, isElite, tradeskillLineIndex, displayTimeLeft = GetQuestTagInfo(questID);

      local tagID, tagName, worldQuestType, rarity, isElite, tradeskillLineIndex = GetQuestTagInfo(questID);

[https://www.townlong-yak.com/framexml/live/Blizzard_ObjectiveTracker/Blizzard_BonusObjectiveTracker.lua/diff](url)
