### ISSUE TITLE
NxQuest.lua:9185:Attempt to index global WorldMapToolTip error

### ISSUE THREAD

**Issue by jerryjoh** [mikepauer/Carbonite.Quests#65]
3606x Carbonite.Quests\NxQuest.lua:9185: attempt to index global 'WorldMapTooltip' (a nil value)
Carbonite.Quests\NxQuest.lua:9185: in function `ScanTip'
Carbonite.Quests\NxQuest.lua:9244: in function `UpdateList'
Carbonite.Quests\NxQuest.lua:9067: in function `func'
Carbonite\Libs\AceTimer-3.0\AceTimer-3.0-17.lua:57: in function <Carbonite\Libs\AceTimer-3.0\AceTimer-3.0.lua:50>

Locals:
bounty = <table> {
 numObjectives = 1
 questID = 50604
 icon = 2203919
 factionID = 0
}
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to index global 'WorldMapTooltip' (a nil value)"
AddObjectives = <function> defined @Carbonite.Quests\NxQuest.lua:9174
_G = <table> {
 ERR_OUT_OF_CHI = "Not enough chi"
 DH_HAVOC_CORE_ABILITY_2 = "Strong melee attack that consumes Fury. If it critical strikes, some Fury is refunded."
 ArmoryOptionsTooltipPanelShowItemCountColorSwatch = ArmoryOptionsTooltipPanelShowItemCountColorSwatch {
 }
 GetTrainerServiceTypeFilter = <function> defined =[C]:-1
 UNIT_NAMES_COMBATLOG_TOOLTIP = "Color unit names."
 SetTrainerServiceTypeFilter = <function> defined =[C]:-1
 LE_GAME_ERR_CHAT_RAID_RESTRICTED_TRIAL = 740
 SPELL_FAILED_CUSTOM_ERROR_71 = "This partygoer wants to dance with you."
 LE_GAME_ERR_PET_SPELL_TARGETS_DEAD = 398
 InterfaceOptionsActionBarsPanelStackRightBarsPixelBorderTOP = InterfaceOptionsActionBarsPanelStackRightBarsPixelBorderTOP {
 }
 StaticPopup4MoneyInputFrameCopperPixelBorderLEFT = StaticPopup4MoneyInputFrameCopperPixelBorderLEFT {
 }
 CompactUnitFrameProfilesGeneralOptionsFrameHealthTextDropdownButtonNormalTexture = CompactUnitFrameProfilesGeneralOptionsFrameHealthTextDropdownButtonNormalTexture {
 }
 PawnItemComparer = <function> defined @Pawn\Pawn.lua:3480
 CombatConfigColorsColorizeEntireLinePixelBorderCENTER = CombatConfigColorsColorizeEntireLinePixelBorderCENTER {
 }
 MultiBarLeftButton7 = MultiBarLeftButton7 {
 }
 AudioOptionsVoicePanelOutputDeviceDropdownButtonHighlightTexture = AudioOptionsVoicePanelOutputDeviceDropdownButtonHighlightTexture {
 }
 LibDugi_UIDropDownMenu_SetSelectedValue = <function> defined @DugisGuideViewerZ\Libs\DropDownMenu\UIDropDownMenu.lua:733
 LFGListInviteDialog_OnEvent = <function> defined @FrameXML\LFGList.lua:2400
 MerchantItem3AltCurrencyFrameItem1Text = MerchantItem3AltCurrencyFrameItem1Text {
 }
 BINDING_NAME_NAMEPLATES = "Show Enemy Name Plates"
 INSTANCE_UNAVAILABLE_OTHER_TEMPORARILY_DISABLED = "%s cannot enter. This instance is temporarily disabled."
 ArmorySpellButton5 = ArmorySpellButton5 {
 }
 MultiBarBottomRightButton8Shine5 = MultiBarBottomRightButton8Shine5 {
 }
 IsReferAFriendLinked = <function> defined =[C]:-1
 UnitFrameManaBar_UnregisterDefaultEvents = <function> defined @FrameXML\UnitFrame.lua:794
 PaperDollTitlesPaneButton13BgTop = PaperDollTitlesPaneButton13BgTop {
 }
 CALENDAR_RAID_RESET_DESCRIPTION = "%1$s resets at %2$s."
 ArmoryMainHandSlot = ArmoryMainHandSlot {
 }
 HasZoneAbility = <function> defined @FrameXML\ZoneAbility.lua:157
 MoneyFrame_OnEvent = <function> defined @FrameXML\MoneyFrame.lua:214
 LE_GAME_ERR_RECRUIT_A_FRIEND_FAILED = 950
 ElvUI_Bar5Button12Shine7 = ElvUI_Bar5Button12Shine7 {
 }
 CompactRaidFrameManagerDisplayFrameHiddenModeToggleTopRight = CompactRaidFrameManagerDisplayFrameHiddenModeToggleTopRight {
 }
 LFGTeleport = <function> defined =[C]:-1
 LE_GAME_ERR_ONLY_ONE_QUIVER = 32
 INT_SPELL_DURATION_HOURS = "%d |4hour:hrs;"
 RaidFrameConvertToRaidButtonPixelBorderTOPRIGHT = RaidFrameConvertToRaidButtonPixelBorderTOPRIGHT {
 }
 ToggleEncounterJournal = <function> defined @FrameXML\UIParent.lua:910
 StackSplitFramePixelBorderTOP = StackSplitFramePixelBorderTOP {
 }
 LOSS_OF_CONTROL_DISPLAY_FEAR = "Feared"
 Graphics_QualityText = Graphics_

**Comment by IrcDirk** [comment]
Fixed
