### ISSUE TITLE
Frame disappearing quickly when mousing over a caged pet in my bag

### ISSUE THREAD

**Issue by Swirrel** [mikepauer/Carbonite.Quests#67]
Hi.
Last time I was online in WoW was 1 week before patch 8.1.5. Now I'm online again (march 16th 2019)... I've updated all my addons inc. my 2 carbonite addons (map and quest)...
A guildie had sent me a gift, that turned out to be a pet. It was a nice thought, but with 985 pets it's getting hard to find a pet that I don't have... As I had the pet my guildie sent me (Nightwreathed Watcher), I noticed that 0,5-3 seconds after mousing over the caged pet the "frame" that popped up, would disappear. I'm not sure the word "frame" is the right word, but you know the "tooltip/frame that pops up on an item, when you mouse over an item... that the thingie I'm talking about.

At first I thought it was Elvui, but it turned out to not be that. I then turned of my pet related addons, but it wasn't those either (Pet Tracker, Rematch, PetBattle Breed ID)...
I simply just grabbed a screenie of which addons was turned on, and then disabled all my addons, for then to turn them on 5-10 at a time and each time mousing over the caged pet, to see if either addons turned on would make a difference. The last I turned on was Carb Map, Carb Quest, BugGrabber, BugSack, BuyEmAll, Chinchilla Minimap, EasyMail and Garrison Mission Manager)...
Then I had a mouse over frame/tooltip issue. Honestly, I turned both my Carb addons off and didn't have mouseover tooltip thingie issue. I turned Carb Map and Carb Quest on and got the issue back. I then turned off Carb Quest and the issue went away again.
Status Quo: Carb Quest is for some strange reason messing with me mousing over the caged pet in my bag. I checked to make sure it wasn't just that 1 pet, and caged Anubisath Idol which is lvl 25. The guildie pet is lvl 1, they're both blue quality.... It's still happening.
But it ONLY happens when I mouse over a caged pet. I have food, pet treats, hp pots, Underlight Angler ect in my bag (just see the screenie)... and mousing over those items, makes the tooltip/frame thingie stationary until I move the mouse over another item.

I can't make a small video for you this time, cus my phone is in for repair and the spare phone I have is so ancient that I'm surprised I can even send and recieve text messages on it...

It's just really odd that Carbonite Quest would affect an item in my bag when those 2 things should have nothing to do with each other in the first place.
I'm adding a screenshot as to show which "frame" I'm having issues with.
Also, I'm not getting any errors or bugs to show.

After another round of screenshots, I turned off everything Carb Quest was set to do (not the addon. Just the options in Quests it self), did a reload and moused over the caged pet in my bag again.. didn't make any change to how the frame thingie is behaving.

![WoWScrnShot_031619_201450](https://user-images.githubusercontent.com/31900265/54480454-b7241e00-4828-11e9-8ec2-aea3b832f24e.jpg)

**Comment by IrcDirk** [comment]
Sorry no issue on my side with caged pets and tootlip, all works fine (with all my addons enabled).

Check only Carbonite + Carbonite Quest enabled. Seems thats other addon.

**Comment by Swirrel** [comment]
Hi.
Sorry for the very long wait for a reply from me. Been super swamped irl so I haven't been online in what appears to be 22 days.
Right now, I have all addons, except Carb map and Carb quest, turned off. I've maded a video off it too and shown about the frame disappearing.
Imgur was acting up, so I hope you can see this vid on youtube https://www.youtube.com/watch?v=_lQrIZ2apIA

It's semi hidden. Only ppl with the link can see the video. At least if youtube is true to their word :)

**Comment by IrcDirk** [comment]
Same setup only Carb + Quests enabled. All works fine no problems :/ Cant reproduce...

**Comment by Swirrel** [comment]
It's strange ... in my book it's strange. Though you haven't been able to reproduce my issue, it would seem that the latest update have fixed the issue entirely. 
What ever, there may have been going on, it's now fixed my end, so I'll be closing the issue.
Once again, thank you for your patience and time.

Cheers

Ps. Have a nice, though belated, easter.

**Comment by Swirrel** [comment]
Hi.
I know I've closed this post, however I need to inform you that in the latest Carbonite Maps Alpha version, the above mentioned issue occurs again. Reverting to the Carbonite Map Release and reinstalling the addon, removes the above mentioned issue.
I know you couldn't reproduce this issue the last time it happend, so I'm hoping that if I come here asap that you might be able to find the differences between the latest Release and the latest Alpha... What ever is the difference or changes between those two, if messes with the mouse over on caged pets.

Again, thank you for your time.
//Jag.
