### ISSUE TITLE
NxQuest.lua:3905: script ran too long Time: 06/19/17 19:44:01

### ISSUE THREAD

**Issue by Thrumbar** [mikepauer/Carbonite.Quests#7]
Only had Carbonite loaded (full).  In Skyhold with my Warrior and was hitting the spacebar hopping around and this error appeared..  Logged off and used Curse client to reload all Carbonite logged in and repeated with error..

Message: Interface\AddOns\Carbonite.Quests\NxQuest.lua:3905: script ran too long
Time: 06/19/17 19:44:01
Count: 1
Stack: Interface\AddOns\Carbonite.Quests\NxQuest.lua:3905: script ran too longInterface\SharedXML\SharedBasicControls.lua:204: in function <Interface\SharedXML\SharedBasicControls.lua:203>
[C]: in function `SetMapByID'
Interface\AddOns\Carbonite.Quests\NxQuest.lua:3905: in function `ScanBlizzQuestDataTimer'
Interface\AddOns\Carbonite.Quests\NxQuest.lua:3869: in function <Interface\AddOns\Carbonite.Quests\NxQuest.lua:3869>

Locals: errorMessage = "Interface\AddOns\Carbonite.Quests\NxQuest.lua:3905: script ran too long"
DisplayMessageInternal = <function> defined @Interface\SharedXML\SharedBasicControls.lua:187
MESSAGE_TYPE_ERROR = 0

**Comment by Thrumbar** [comment]
Put a ; (semicolon) and the end of 3905 and get this error instead.

Message: Interface\AddOns\Carbonite.Quests\NxQuest.lua:2976: script ran too long
Time: 06/19/17 19:57:41
Count: 1
Stack: Interface\AddOns\Carbonite.Quests\NxQuest.lua:2976: script ran too longInterface\SharedXML\SharedBasicControls.lua:204: in function <Interface\SharedXML\SharedBasicControls.lua:203>
[C]: in function `format'
Interface\AddOns\Carbonite.Quests\NxQuest.lua:2976: in function `ProcessQuestDB'
Interface\AddOns\Carbonite.Quests\NxQuest.lua:3106: in function <Interface\AddOns\Carbonite.Quests\NxQuest.lua:3106>

Locals: errorMessage = "Interface\AddOns\Carbonite.Quests\NxQuest.lua:2976: script ran too long"
DisplayMessageInternal = <function> defined @Interface\SharedXML\SharedBasicControls.lua:187
MESSAGE_TYPE_ERROR = 0

**Comment by Thrumbar** [comment]
Remover the ; (semicolon) from 3905 I put at the and put on at end of the 2 next lines and no error..

			SetMapByID(mapId)			-- Triggers WORLD_MAP_UPDATE, which calls MapChanged
			local cont = Nx.Map.MapWorldInfo[mapId].Cont;
			local info = Map.MapInfo[cont];

**Comment by Thrumbar** [comment]
Nuts cannot replicate this anymore..

**Comment by IrcDirk** [comment]
This shitty blizz "script ran too long" accours sometimes randomly... Its dependend on your computer performance in that time. It occurs  So if this doesnt happen like 10 times in a row and after computer restart, it isnt something important.
