### ISSUE TITLE
Tried porting issue #37 from IRCDIRK repo for Calassic for group quest getting error #161

### ISSUE THREAD

**Issue by Thrumbar** [mikepauer/Carbonite.Quests#72]
IrcDirk/Carbonite-Classic@6fe2d5d
IrcDirk/Carbonite-Classic@7fe1ba3
IrcDirk/Carbonite-Classic@3b17bbc
IrcDirk/Carbonite-Classic@8fd5676
IrcDirk/Carbonite-Classic@c9f313a

3x Carbonite.Quests\NxQuest.lua:3836: attempt to concatenate global 'desc' (a nil value)
Carbonite.Quests\NxQuest.lua:3836: in function `RecordQuestsLog'
Carbonite.Quests\NxQuest.lua:3503: in function `RecordQuests'
Carbonite.Quests\NxQuest.lua:6763: in function <Carbonite.Quests\NxQuest.lua:6749>
SharedXML\C_TimerAugment.lua:16: in function <SharedXML\C_TimerAugment.lua:14>

Locals:
self = <table> {
 IconTracking = <table> {
 }
 UnpackCategory = <function> defined @Carbonite.Quests\NxQuest.lua:10582
 DailyTypes = <table> {
 }
 IsTargeted = <function> defined @Carbonite.Quests\NxQuest.lua:10348
 Menu_OnTrack = <function> defined @Carbonite.Quests\NxQuest.lua:3270
 GetQuestReward = <function> defined @Carbonite.Quests\NxQuest.lua:3324
 DecodeComRcv = <function> defined @Carbonite.Quests\NxQuest.lua:11218
 MsgNotInDB = <function> defined @Carbonite.Quests\NxQuest.lua:5273
 Watch = <table> {
 }
 PartyStartSend = <function> defined @Carbonite.Quests\NxQuest.lua:11481
 SortQuests = <function> defined @Carbonite.Quests\NxQuest.lua:4348
 NullQuest = <function> defined @Carbonite.Quests\NxQuest.lua:11628
 CheckQuestSE = <function> defined @Carbonite.Quests\NxQuest.lua:3208
 GetFromPlyr = <function> defined @Carbonite.Quests\NxQuest.lua:5087
 Custom = <table> {
 }
 TTChange = <table> {
 }
 TooltipProcess2 = <function> defined @Carbonite.Quests\NxQuest.lua:5382
 IdToCurQ = <table> {
 }
 PerColors = <table> {
 }
 GetClosestObjectivePos = <function> defined @Carbonite.Quests\NxQuest.lua:10862
 RecordQuestsLog = <function> defined @Carbonite.Quests\NxQuest.lua:3510
 ExtractTitle = <function> defined @Carbonite.Quests\NxQuest.lua:4324
 CalcCNumMax = <function> defined @Carbonite.Quests\NxQuest.lua:4134
 UnpackObjective = <function> defined @Carbonite.Quests\NxQuest.lua:10620
 GetQuestObjectiveInfo = <function> defined @Carbonite.Quests\NxQuest.lua:4292
 FindCur = <function> defined @Carbonite.Quests\NxQuest.lua:4811
 TooltipProcess = <function> defined @Carbonite.Quests\NxQuest.lua:5358
 SelectBlizz = <function> defined @Carbonite.Quests\NxQuest.lua:3378
 UnpackNext = <function> defined @Carbonite.Quests\NxQuest.lua:10573
 ShowUIPanel = <function> defined @Carbonite.Quests\NxQuest.lua:5886
 CapturePlyrData = <table> {
 }
 GetObjectiveType = <function> defined @Carbonite.Quests\NxQuest.lua:10633
 PartyUpdateTimer = <function> defined @Carbonite.Quests\NxQuest.lua:11473
 MapChanged = <function> defined @Carbonite.Quests\NxQuest.lua:4026
 OnParty_members_changed = <function> defined @Carbonite.Quests\NxQuest.lua:11314
 TrackedAchievements = <table> {
 }
 UpdateQuestDetails = <function> defined @Carbonite.Quests\NxQuest.lua:8321
 DailyIds = <table> {
 }
 CalcDesc = <function> defined @Carbonite.Quests\NxQuest.lua:4274
 QLocColors = <table> {
 }
 CalcPreviousDone = <function> defined @Carbonite.Quests\NxQuest.lua:4177
 AccessAllQuests = <function> defined @Carbonite.Quests\NxQuest.lua:3458
 IconOnMouseDown = <function> defined @Carbonite.Quests\NxQuest.lua:8266
 UpdateGiverIconMenu = <function> defined @Carbonite.Quests\NxQuest.lua:10243
 WatchAtLogin = <function> defined @Carbonite.Quests\NxQuest.lua:4918
 CreateLink = <function> defined @Carbonite.Quests\NxQuest.lua:4316
 LightHeadedAttach = <function> defined @Carbonite.Quests\NxQuest.lua:5954
 RecordQuestAcceptOrFinish = <function> defined @Carbonite.Quests\NxQuest.lua:4470
 Goto = <function> defined @Carbonite.Quests\NxQuest.lua:4948
 InitQuestCharacter = <function> defined @Carbonite.Quests\NxQuest.lua:2174
 RealQEntries = 40
 AcceptQuest = <function> defined @Carbonite.Quests\NxQuest.lua:3304
 GetHistoryTimer = <function> defined @Carbonite.Quests\NxQuest.lua:4227
 Requirements = <table> {
 }
 TellPartyOfChanges = <function> defined @Carbonite.Quests\NxQuest.lu

**Comment by IrcDirk** [comment]
Didnt saw that... Will test this in future.

**Comment by Thrumbar** [comment]
Getting spam from quest when doing world quest..  The quest in question is to gather items in legion but it also spams gather quest like for herbs.

https://youtu.be/pm6E8-VmQM8

**Comment by IrcDirk** [comment]
Did they updated it? Becouse they are sending this data too you ;)

**Comment by Thrumbar** [comment]
https://youtu.be/EEihxL9zVJA

**Comment by IrcDirk** [comment]
Set "Broadcast after number of changes" to 999, this is default value and u should not get this spam. Test and report back ;)

**Comment by IrcDirk** [comment]
So it works? :D
