### ISSUE TITLE
Carbonite.Quests\NxQuest.lua:11881: bad argument #1 to 'pairs' (table expected, got nil)

### ISSUE THREAD

**Issue by speder12** [mikepauer/Carbonite.Quests#73]

**Comment by speder12** [comment]
1x Carbonite.Quests\NxQuest.lua:11881: bad argument #1 to 'pairs' (table expected, got nil)
[C]: in function `pairs'
Carbonite.Quests\NxQuest.lua:11881: in function <Carbonite.Quests\NxQuest.lua:11867>
SharedXML\C_TimerAugment.lua:16: in function <SharedXML\C_TimerAugment.lua:14>

Locals:
(*temporary) = nil
(*temporary) = "table expected, got nil"
 = <function> defined =[C]:-1

**Comment by Thrumbar** [comment]
Got this quest while on quest A World Worth Saving upon entering Halls of Orientation.

1x Carbonite.Quests\NxQuest.lua:11881: bad argument #1 to 'pairs' (table expected, got nil)
[string "=[C]"]: in function `pairs'
[string "@Carbonite.Quests\NxQuest.lua"]:11881: in function <Carbonite.Quests\NxQuest.lua:11867>
[string "@SharedXML\C_TimerAugment.lua"]:16: in function <SharedXML\C_TimerAugment.lua:14>

Locals:
(*temporary) = nil
(*temporary) = "table expected, got nil"
 = <function> defined =[C]:-1
