### ISSUE TITLE
Carbonite 8.3.01 error message

### ISSUE THREAD

**Issue by speder12** [mikepauer/Carbonite.Quests#75]
430x Carbonite\NxTravel.lua:517: attempt to call global 'GetMapNameByID' (a nil value)
[string "@Carbonite\NxTravel.lua"]:517: in function `MakePath'
[string "@Carbonite\NxMap.lua"]:5991: in function `CalcTracking'
[string "@Carbonite\NxMap.lua"]:9636: in function `GotoPlayer'
[string "@Carbonite.Quests\NxQuest.lua"]:10499: in function `TrackOnMap'
[string "@Carbonite.Quests\NxQuest.lua"]:10114: in function `ClearCompleted'
[string "@Carbonite.Quests\NxQuest.lua"]:6953: in function `LogUpdate'
[string "@Carbonite.Quests\NxQuest.lua"]:6747: in function <Carbonite.Quests\NxQuest.lua:6732>
[string "@SharedXML\C_TimerAugment.lua"]:16: in function <SharedXML\C_TimerAugment.lua:14>

Locals:
self = <table> {
 LegionFlyName = "Pfadfinder der Verheerten Inseln"
 CaptureTaxi = <function> defined @Carbonite\NxTravel.lua:104
 UnregisterAllEvents = <function> defined @TomTom\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:174
 MakePath = <function> defined @Carbonite\NxTravel.lua:376
 OnTaximap_opened = <function> defined @Carbonite\NxTravel.lua:91
 FindConnection = <function> defined @Carbonite\NxTravel.lua:749
 TaxiFindNodeFromRouteXY = <function> defined @Carbonite\NxTravel.lua:241
 DebugCaptureTaxi = <function> defined @Carbonite\NxTravel.lua:850
 Travel = <table> {
 }
 TaxiCalcTime = <function> defined @Carbonite\NxTravel.lua:169
 FindFlight = <function> defined @Carbonite\NxTravel.lua:611
 Add = <function> defined @Carbonite\NxTravel.lua:55
 RegisterMessage = <function> defined @TomTom\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:90
 UnregisterMessage = <function> defined @TomTom\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:153
 VisitedMapIds = <table> {
 }
 GetRidingSkill = <function> defined @Carbonite\NxTravel.lua:902
 SendMessage = <function> defined @TomTom\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:59
 TaxiSaveTime = <function> defined @Carbonite\NxTravel.lua:336
 FindClosest = <function> defined @Carbonite\NxTravel.lua:696
 Speed = 0.355556
 Init = <function> defined @Carbonite\NxTravel.lua:30
 RegisterEvent = <function> defined @TomTom\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:90
 UnregisterAllMessages = <function> defined @TomTom\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:174
 FlyingMount = false
 TaxiFindConnectionTime = <function> defined @Carbonite\NxTravel.lua:262
 PandariaFlyName = "Weisheit der Vier Winde"
 WrathFlyName = "Kaltwetterflug"
 DraenorFlyName = "Pfadfinder von Draenor"
 AzerothFlyName = "Fluglizenz"
 TakeTaxiNode = <function> defined @Carbonite\NxTravel.lua:136
 TaxiTimer = <function> defined @Carbonite\NxTravel.lua:321
 UnregisterEvent = <function> defined @TomTom\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:153
 OrigTakeTaxiNode = <function> defined @ZygorGuidesViewer\Libs\LibTaxi-1.0\LibTaxi-1.0.lua:871
}
tracking = <table> {
}
srcMapId = 1
srcX = -1491.180840
srcY = -104.025652
dstMapId = 85
dstX = -1569.827449
dstY = -202.711350
targetType = "Q"
Map = <table> {
 Menu_OnTrackPlyr = <function> defined @Carbonite\NxMap.lua:2938
 GetInstanceID = <function> defined @Carbonite\NxMap.lua:9420
 ZoneOverlays = <table> {
 }
 GetZoneAchievement = <function> defined @Carbonite\NxMap.lua:11063
 MinimapOwnInit = <function> defined @Carbonite\NxMap.lua:1961
 RestoreBlizzBountyMap = <function> defined @Carbonite\NxMap.lua:3310
 MapLevels = <table> {
 }
 MinimapSetScale = <function> defined @Carbonite\NxMap.lua:2580
 OnButToggleGuide = <function> defined @Carbonite\NxMap.lua:1656
 MinimapOnMouseDown = <function> defined @Carbonite\NxMap.lua:2077
 SetToCurrentZone = <function> defined @Carbonite\NxMap.lua:9502
 GetIconStatic = <function> defined @Carbonite\NxMap.lua:8526
 UpdateToolBar = <function> defined @Carbonite\NxMap.lua:1278
 Menu_OnBackgndAlphaFade = <function> defined @Carbonite\NxMap.lua:2843
 BlizzToggleWorldMap = <function> defined @Carbonite\NxMap.lua:3337
 Menu_OnMapDebugFullCoords = <function> defined @Carbonite\NxMap.lua:2889
 ClipFrameByMapType = <function> defined @Carbonite\NxMap.lua:7151
 ZandalarMapBlks = <table> {
 }
 ResetIcons = <function> defined @Carbonite\NxMap.lua:825

**Comment by IrcDirk** [comment]
Same as #76
