### ISSUE TITLE
Interface\AddOns\Carbonite\NxTravel.lua:814: attempt to index field 'Connections' (a nil value)

### ISSUE THREAD

**Issue by speder12** [mikepauer/Carbonite.Quests#76]
Message: Interface\AddOns\Carbonite\NxTravel.lua:814: attempt to index field 'Connections' (a nil value)
Time: Tue Feb  4 04:57:22 2020
Count: 1666
Stack: Interface\AddOns\Carbonite\NxTravel.lua:814: attempt to index field 'Connections' (a nil value)
[string "@Interface\AddOns\Carbonite\NxTravel.lua"]:814: in function `FindConnection'
[string "@Interface\AddOns\Carbonite\NxTravel.lua"]:723: in function `FindClosest'
[string "@Interface\AddOns\Carbonite\NxTravel.lua"]:613: in function `FindFlight'
[string "@Interface\AddOns\Carbonite\NxTravel.lua"]:555: in function `MakePath'
[string "@Interface\AddOns\Carbonite\NxMap.lua"]:5991: in function `CalcTracking'
[string "@Interface\AddOns\Carbonite\NxMap.lua"]:5944: in function `?'
[string "@Interface\AddOns\Carbonite\NxMap.lua"]:5122: in function `Update'
[string "@Interface\AddOns\Carbonite\NxMap.lua"]:3999: in function <Interface\AddOns\Carbonite\NxMap.lua:3883>

Locals: self = <table> {
 LegionFlyName = "Pfadfinder der Verheerten Inseln"
 CaptureTaxi = <function> defined @Interface\AddOns\Carbonite\NxTravel.lua:104
 UnregisterAllEvents = <function> defined @Interface\AddOns\Carbonite\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:174
 MakePath = <function> defined @Interface\AddOns\Carbonite\NxTravel.lua:376
 OnTaximap_opened = <function> defined @Interface\AddOns\Carbonite\NxTravel.lua:91
 FindConnection = <function> defined @Interface\AddOns\Carbonite\NxTravel.lua:749
 TaxiFindNodeFromRouteXY = <function> defined @Interface\AddOns\Carbonite\NxTravel.lua:241
 DebugCaptureTaxi = <function> defined @Interface\AddOns\Carbonite\NxTravel.lua:850
 Travel = <table> {
 }
 TaxiCalcTime = <function> defined @Interface\AddOns\Carbonite\NxTravel.lua:169
 FindFlight = <function> defined @Interface\AddOns\Carbonite\NxTravel.lua:611
 Add = <function> defined @Interface\AddOns\Carbonite\NxTravel.lua:55
 RegisterMessage = <function> defined @Interface\AddOns\Carbonite\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:90
 UnregisterMessage = <function> defined @Interface\AddOns\Carbonite\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:153
 VisitedMapIds = <table> {
 }
 GetRidingSkill = <function> defined @Interface\AddOns\Carbonite\NxTravel.lua:902
 SendMessage = <function> defined @Interface\AddOns\Carbonite\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:59
 TaxiSaveTime = <function> defined @Interface\AddOns\Carbonite\NxTravel.lua:336
 FindClosest = <function> defined @Interface\AddOns\Carbonite\NxTravel.lua:696
 Speed = 0.222222
 Init = <function> defined @Interface\AddOns\Carbonite\NxTravel.lua:30
 RegisterEvent = <function> defined @Interface\AddOns\Carbonite\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:90
 UnregisterAllMessages = <function> defined @Interface\AddOns\Carbonite\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:174
 FlyingMount = false
 TaxiFindConnectionTime = <function> defined @Interface\AddOns\Carbonite\NxTravel.lua:262
 PandariaFlyName = "Weisheit der Vier Winde"
 WrathFlyName = "Kaltwetterflug"
 DraenorFlyName = "Pfadfinder von Draenor"
 AzerothFlyName = "Fluglizenz"
 TakeTaxiNode = <function> defined @Interface\AddOns\Carbonite\NxTravel.lua:136
 TaxiTimer = <function> defined @Interface\AddOns\Carbonite\NxTravel.lua:321
 UnregisterEvent = <function> defined @Interface\AddOns\Carbonite\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:153
 OrigTakeTaxiNode = <function> defined =[C]:-1
}
srcMapId = 1
srcX = -1657.848487
srcY = -12.342633
dstMapId = 88
dstX = -2505.951456
dstY = 439.444150
skipIndirect = nil
winfo = <table> {
 1 = <table> {
 }
 7 = <table> {
 }
 10 = <table> {
 }
 12 = <table> {
 }
 13 = <table> {
 }
 14 = <table> {
 }
 15 = <table> {
 }
 17 = <table> {
 }
 18 = <table> {
 }
 21 = <table> {
 }
 22 = <table> {
 }
 23 = <table> {
 }
 24 = <table> {
 }
 25 = <table> {
 }
 26 = <table> {
 }
 27 = <table> {
 }
 32 = <table> {
 }
 36 = <table> {
 }
 37 = <table> {
 }
 42 = <table> {
 }
 47 = <table> {
 }
 48 = <table> {
 }
 49 = <table> {
 }
 50 = <table>

**Comment by speder12** [comment]
carbonite maps only works carbonite quests makes problems all addon deactivated with the same result

**Comment by IrcDirk** [comment]
When did this error happened? Cant reproduce :/

**Comment by speder12** [comment]
Message: Interface\AddOns\Carbonite.Warehouse\NxWarehouse.lua:843: hooksecurefunc(): SetAuctionItem is not a function
Time: Tue Feb  4 11:06:03 2020
Count: 1
Stack: Interface\AddOns\Carbonite.Warehouse\NxWarehouse.lua:843: hooksecurefunc(): SetAuctionItem is not a function
[string "=[C]"]: in function `hooksecurefunc'
[string "@Interface\AddOns\Carbonite.Warehouse\NxWarehouse.lua"]:843: in function `func'
[string "@Interface\AddOns\Carbonite\Libs\AceTimer-3.0\AceTimer-3.0.lua"]:57: in function <...\AddOns\Carbonite\Libs\AceTimer-3.0\AceTimer-3.0.lua:50>

Locals:

**Comment by speder12** [comment]
yesterday i was a druid in durotar because the pointer didn't go anymore

**Comment by IrcDirk** [comment]
Dont mix two different issues :/

**Comment by IrcDirk** [comment]
This should be reported in Main Carbonite repository...
