### ISSUE TITLE
Interface\AddOns\Carbonite.Warehouse\NxWarehouse.lua:843: hooksecurefunc(): SetAuctionItem is not a function

### ISSUE THREAD

**Issue by speder12** [mikepauer/Carbonite.Quests#77]
Message: Interface\AddOns\Carbonite.Warehouse\NxWarehouse.lua:843: hooksecurefunc(): SetAuctionItem is not a function
Time: Tue Feb 4 11:06:03 2020
Count: 1
Stack: Interface\AddOns\Carbonite.Warehouse\NxWarehouse.lua:843: hooksecurefunc(): SetAuctionItem is not a function
[string "=[C]"]: in function hooksecurefunc' [string "@Interface\AddOns\Carbonite.Warehouse\NxWarehouse.lua"]:843: in function func'
[string "@interface\AddOns\Carbonite\Libs\AceTimer-3.0\AceTimer-3.0.lua"]:57: in function <...\AddOns\Carbonite\Libs\AceTimer-3.0\AceTimer-3.0.lua:50>

**Comment by IrcDirk** [comment]
Should be reported on Warehouse module repository...
