### ISSUE TITLE
carbonite quests crashes on login

### ISSUE THREAD

**Issue by qlesz** [mikepauer/Carbonite.Quests#9]
carbonite quests crashes on login and it makes carbonite map useless (all icons dissapear)

Date: 2017-06-30 20:13:53
ID: 1
Error occured in: Global
Count: 1
Message: ..\AddOns\Carbonite.Quests\NxQuest.lua line 7795:
   attempt to call method 'ClipFrameByMapType' (a nil value)
Debug:
   Carbonite.Quests\NxQuest.lua:7795: UpdateIcons()
   Carbonite\NxMap.lua:4845: Update()
   Carbonite\NxMap.lua:3812:
      Carbonite\NxMap.lua:3696
Locals:
self = <table> {
 IconTracking = <table> {
 }
 UnpackCategory = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:10214
 DailyTypes = <table> {
 }
 IsTargeted = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:9980
 Menu_OnTrack = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:3185
 GetQuestReward = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:3238
 DecodeComRcv = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:10850
 MsgNotInDB = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:5149
 Watch = <table> {
 }
 PartyStartSend = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:11087
 GOpts = <table> {
 }
 NullQuest = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:11231
 CheckQuestSE = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:3123
 GetFromPlyr = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:4963
 Custom = <table> {
 }
 TTChange = <table> {
 }
 OldMap = 1014
 IdToCurQ = <table> {
 }
 PerColors = <table> {
 }
 GetClosestObjectivePos = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:10494
 RecordQuestsLog = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:3423
 ExtractTitle = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:4197
 CalcCNumMax = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:4019
 ScanBlizzQuestDataZone = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:3947
 FindCur = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:4686
 TooltipProcess = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:5234
 SelectBlizz = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:3291
 UnpackNext = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:10205
 ShowUIPanel = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:5767
 CapturePlyrData = <table> {
 }
 GetObjectiveType = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:10265
 PartyUpdateTimer = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:11080
 MapChanged = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:3925
 OnParty_members_changed = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:10946
 AlchemistsApprenticeData = <table> {
 }
 UpdateQuestDetails = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:8086
 DailyIds = <table> {
 }
 CalcDesc = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:4160
 QLocColors = <table> {
 }
 CalcPreviousDone = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:4062
 AccessAllQuests = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:3371
 IconOnMouseDown = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:8031
 UpdateGiverIconMenu = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:9875
 WatchAtLogin = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:4793
 CreateLink = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:4189
 LightHeadedAttach = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:5835
 RecordQuestAcceptOrFinish = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:4345
 ExpandQuests = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:3301
 InitQuestCharacter = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:2113
 RealQEntries = 18
 AcceptQuest = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:3218
 GetHistoryTimer = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:4112
 Requirements = <table> {
 }
 TellPartyOfChanges = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:4608
 Cols = <table> {
 }
 CreateGiverIconMenu = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:9799
 ScanBlizzQuestDataTimer = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:38
AddOns:
  Swatter, v7.4.5714 (TasmanianThylacine)
  Atlas, vv1.42.01
  AtlasBurningCrusade, vv1.42.01
  AtlasCataclysm, vv1.42.00
  AtlasClassicWoW, vv1.42.00
  AtlasClassOrderHalls, vv1.42.00
  AtlasDungeonLocs, vv1.42.00
  AtlasLegion, vv1.42.00
  AtlasMistsofPandaria, vv1.42.01
  AtlasOutdoorRaids, vv1.42.00
  AtlasScenarios, vv1.42.00
  AtlasWarlordsofDraenor, vv1.42.00
  AtlasWorldEvents, vv3.22
  AtlasWrathoftheLichKing, vv1.42.01
  AtlasLoot, vv8.04.04
  AtlasLootBurningCrusade, vv8.04.04
  AtlasLootCataclysm, vv8.04.04
  AtlasLootClassic, vv8.04.04
  AtlasLootLegion, vv8.04.04
  AtlasLootMistsofPandaria, vv8.04.04
  AtlasLootWarlordsofDraenor, vv8.04.04
  AtlasLootWrathoftheLichKing, vv8.04.04
  AtlasMajorCitiesEnhanced, vv1.15
  AucAdvanced, v7.4.5714 (TasmanianThylacine)
  AucFilterBasic, v7.4.5714 (TasmanianThylacine)
  AucFilterOutlier, v7.4.5714.5459(7.4/embedded)
  AucMatchUndercut, v7.4.5714.5585(7.4/embedded)
  AucStatHistogram, v7.4.5714 (TasmanianThylacine)
  AucStatiLevel, v7.4.5714 (TasmanianThylacine)
  AucStatPurchased, v7.4.5714 (TasmanianThylacine)
  AucStatSales, v7.4.5714.5598(7.4/embedded)
  AucStatSimple, v7.4.5714 (TasmanianThylacine)
  AucStatStdDev, v7.4.5714 (TasmanianThylacine)
  AucStatWOWEcon, v7.4.5714.5613(7.4/embedded)
  AucUtilAHWindowControl, v7.4.5714.5575(7.4/embedded)
  AucUtilAppraiser, v7.4.5714.5704(7.4/embedded)
  AucUtilAskPrice, v7.4.5714.5599(7.4/embedded)
  AucUtilAutoMagic, v7.4.5714.5686(7.4/embedded)
  AucUtilCompactUI, v7.4.5714.5694(7.4/embedded)
  AucUtilEasyBuyout, v7.4.5714.5576(7.4/embedded)
  AucUtilFixAH, v7.4.5714 (TasmanianThylacine)
  AucUtilItemSuggest, v7.4.5714.5651(7.4/embedded)
  AucUtilPriceLevel, v7.4.5714.5633(7.4/embedded)
  AucUtilScanButton, v7.4.5714.5631(7.4/embedded)
  AucUtilScanFinish, v7.4.5714.5588(7.4/embedded)
  AucUtilScanProgress, v7.4.5714.4979(7.4/embedded)
  AucUtilScanStart, v7.4.5714.5347(7.4/embedded)
  AucUtilSearchUI, v7.4.5714.5710(7.4/embedded)
  AucUtilSimpleAuction, v7.4.5714.5705(7.4/embedded)
  AucUtilVendMarkup, v7.4.5714.4828(7.4/embedded)
  Babylonian, v5.1.DEV.332(/embedded)
  BadBoy, vv7.2.221
  BadBoyCCleaner, vv7.2.0
  Bartender4, v4.7.7
  BeanCounter, v7.4.5714 (TasmanianThylacine)
  BuyEmAll, v3.3.5
  Carbonite, v7.2.5
  CarboniteInfo, v7.2.0
  CarboniteNotes, v7.2.0
  CarboniteQuests, v7.2.5
  CarboniteSocial, v7.2.0
  CarboniteWarehouse, v7.2.0
  CarboniteWeekly, v7.2.0
  ClassOrderHallsComplete, v1.17
  Configator, v5.1.DEV.406(/embedded)
  CTATracker, v
  DBMCore, v7.2.11
  DBMDefaultSkin, v
  DBMStatusBarTimers, v
  DebugLib, v5.1.DEV.337(/embedded)
  Enchantrix, v7.4.5714 (TasmanianThylacine)
  EnchantrixBarker, v7.4.5714 (TasmanianThylacine)
  epgp, vv5.12.12
  epgplootmaster, v6.71
  epgplootmasterml, v6.71
  GearCheck, vv4.4
  GottaGoFast, v26500
  GottaGoFastHistory, v26500
  HandyNotes, vv1.4.13
  HandyNotesBrokenShore, vv1.18
  HandyNotesDraenorTreasures, v1.20a
  HandyNotesLegionTreasures, v1
  LibExtraTip, v5.12.DEV.423(/embedded)
  MoveAnything, v16.2.0
  OmniCC, v7.2.1
  Overachiever, v0.99.8
  OverachieverTabs, v0.99.8
  Pawn, v2.2.8a
  PersonalLootHelper, v1.31
  Postal, vv3.5.8
  Prat30, vr1078      
  Prat30Libraries, v
  ReputationBars, v7.2.1
  Skada, v1.6.8
  SkadaFriendlyFire, v1.4.1
  Skillet, v3.25
  SlideBar, v7.4.5714 (TasmanianThylacine)
  Stubby, v7.4.5714 (TasmanianThylacine)
  TellMeWhen, v8.4.0
  TellMeWhenOptions, v
  TipHelper, v5.12.DEV.405(/embedded)
  WeakAuras, v2.4.6
  WorldQuestGroupFinder, v0.26.3
  WorldQuestTracker, v
  BlizRuntimeLib_enUS v7.2.5.70200 <none>
  (ck=df0)

**Comment by mikepauer** [comment]
You didn't update Carbonite Maps. The latest quests release requires the latest maps release.

**Comment by mikepauer** [comment]
If you got the latest quests release through curse client and not that you installed it yourself, check your carbonite maps settings to make sure it's set to also install alpha releases, or disable alpha releases for quests so it reverts to the last one.
