### ISSUE TITLE
Changing font size error

### ISSUE THREAD

**Issue by Commenterry** [mikepauer/Carbonite.Quests#94]
When I try to use the options menu to change the font size of the quest watch panel, I get the following error:

Message: Interface\AddOns\Carbonite.Quests\NxQuest.lua:9837: attempt to compare nil with number
Time: Mon Nov  2 01:45:51 2020
Count: 12
Stack: Interface\AddOns\Carbonite.Quests\NxQuest.lua:9837: attempt to compare nil with number
[string "@Interface\AddOns\Carbonite.Quests\NxQuest.lua"]:9837: in function `UpdateList'
[string "@Interface\AddOns\Carbonite.Quests\NxQuest.lua"]:9120: in function `func'
[string "@Interface\AddOns\DataStore\libs\AceTimer-3.0\AceTimer-3.0.lua"]:57: in function <...\AddOns\DataStore\libs\AceTimer-3.0\AceTimer-3.0.lua:50>

Locals: self = <table> {
 UpdateList = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:9129
 Win = <table> {
 }
 Menu_OnRemoveWatch = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:8910
 WinUpdateFade = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:9869
 ClearAutoTarget = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:9018
 ShowUpdate = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:9852
 ClosestCur = <table> {
 }
 ClearCompleted = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:10105
 OnUpdateTimer = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:9038
 Open = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:8634
 AddCustom = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:9087
 ButATarget = <table> {
 }
 ButSwap = <table> {
 }
 Menu = <table> {
 }
 Add = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:10084
 Watched = <table> {
 }
 Menu_OnRemoveAllWatches = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:8957
 Menu_OnAbandon = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:8952
 Update = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:9072
 CalcDistCnt = 25
 CalcDistI = 1
 FlashColor = 1
 Menu_OnShowMap = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:8926
 Opened = true
 RemoveWatch = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:8971
 ClearCustom = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:9083
 RMenu = <table> {
 }
 WatchMenu = <table> {
 }
 Menu_OnShare = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:8936
 List = <table> {
 }
 MenuPri = <table> {
 }
 Set = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:10002
 ButShowParty = <table> {
 }
 ButQGivers = <table> {
 }
 ButShowOnMap = <table> {
 }
 OnTimer = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:9100
 OnListEvent = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:9887
 Menu_OnShowQuest = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:8917
 SetSortMode = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:9034
 ButMenu = <table> {
 }
 Menu_OnLinkQuest = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:8931
 OnWin = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:8904
 FixedChange = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:8897
 ButPri = <table> {
 }
}
Nx = <table> {
 GetDataToolBar = <function> defined @Interface\AddOns\Carbonite\Carbonite.lua:1932
 modules = <table> {
 }
 CancelTimer = <function> defined @Interface\AddOns\DataStore\libs\AceTimer-3.0\AceTimer-3.0.lua:147
 Quest = <table> {
 }
 OnUnit_spellcast_sent = <function> defined @Interface\AddOns\Carbonite\Carbonite.lua:1162
 IsGathering = <function> defined @Interface\AddOns\Carbonite\Carbonite.lua:3065
 prt = <function> defined @Interface\AddOns\Carbonite\NxUI.lua:133
 BarData = <table> {
 }
 prtVar = <function> defined @Interface\AddOns\Carbonite\NxUI.lua:204
 ScheduleTimer = <function> defined @Interface\AddOns\DataStore\libs\AceTimer-3.0\AceTimer-3.0.lua:94
 GroupMembers = <table> {
 }
 ADDON_LOADED = <function> defined @Interface\AddOns\Carbonite\Carbonite.lua:901
 prtFrame = <function> defined @Inter"

If I try to close the error window, it keeps opening up again. If I reload UI, it stops the error from popping up again and also my changes are saved.

**Comment by IrcDirk** [comment]
Sorry cant reproduce :( Works fine on my side. Disable all addons just leave Carbonite + Modules enabled, then check if this still persists.

**Comment by IrcDirk** [comment]
It might be "DataStore" addon which might have old Ace3 libraries.

**Comment by commonterry** [comment]
I figured you were probably right, but after disabling all my addins except for Carbonite main and quests, I still get an error.

Message: Interface\AddOns\Carbonite.Quests\NxQuest.lua:9837: attempt to compare nil with number
Time: Mon Nov  2 23:55:01 2020
Count: 21
Stack: Interface\AddOns\Carbonite.Quests\NxQuest.lua:9837: attempt to compare nil with number
[string "@Interface\AddOns\Carbonite.Quests\NxQuest.lua"]:9837: in function `UpdateList'
[string "@Interface\AddOns\Carbonite.Quests\NxQuest.lua"]:9120: in function `func'
[string "@Interface\AddOns\Carbonite\Libs\AceTimer-3.0\AceTimer-3.0.lua"]:57: in function <...\AddOns\Carbonite\Libs\AceTimer-3.0\AceTimer-3.0.lua:50>

Locals: self = <table> {
 UpdateList = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:9129
 Win = <table> {
 }
 Menu_OnRemoveWatch = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:8910
 WinUpdateFade = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:9869
 ClearAutoTarget = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:9018
 ShowUpdate = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:9852
 ClosestCur = <table> {
 }
 ClearCompleted = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:10105
 OnUpdateTimer = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:9038
 Open = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:8634
 AddCustom = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:9087
 ButATarget = <table> {
 }
 ButSwap = <table> {
 }
 Menu = <table> {
 }
 Add = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:10084
 Watched = <table> {
 }
 Menu_OnRemoveAllWatches = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:8957
 Menu_OnAbandon = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:8952
 Update = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:9072
 CalcDistCnt = 25
 CalcDistI = 1
 FlashColor = 0
 Menu_OnShowMap = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:8926
 Opened = true
 RemoveWatch = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:8971
 ClearCustom = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:9083
 RMenu = <table> {
 }
 WatchMenu = <table> {
 }
 Menu_OnShare = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:8936
 List = <table> {
 }
 MenuPri = <table> {
 }
 Set = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:10002
 ButShowParty = <table> {
 }
 ButQGivers = <table> {
 }
 ButShowOnMap = <table> {
 }
 OnTimer = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:9100
 OnListEvent = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:9887
 Menu_OnShowQuest = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:8917
 SetSortMode = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:9034
 ButMenu = <table> {
 }
 Menu_OnLinkQuest = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:8931
 OnWin = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:8904
 FixedChange = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:8897
 ButPri = <table> {
 }
}
Nx = <table> {
 GetDataToolBar = <function> defined @Interface\AddOns\Carbonite\Carbonite.lua:1932
 modules = <table> {
 }
 CancelTimer = <function> defined @Interface\AddOns\Carbonite\Libs\AceTimer-3.0\AceTimer-3.0.lua:147
 Quest = <table> {
 }
 OnUnit_spellcast_sent = <function> defined @Interface\AddOns\Carbonite\Carbonite.lua:1162
 IsGathering = <function> defined @Interface\AddOns\Carbonite\Carbonite.lua:3065
 prt = <function> defined @Interface\AddOns\Carbonite\NxUI.lua:133
 BarData = <table> {
 }
 prtVar = <function> defined @Interface\AddOns\Carbonite\NxUI.lua:204
 ScheduleTimer = <function> defined @Interface\AddOns\Carbonite\Libs\AceTimer-3.0\AceTimer-3.0.lua:94
 GroupMembers = <table> {
 }
 ADDON_LOADED = <function> defined @Interface\AddOns\Carbonite\Carbonite.lua:901
 prtFrame = <function> defined @Inter

**Comment by IrcDirk** [comment]
Still cant reproduce. Show the place where u are changing the font.

**Comment by commonterry** [comment]
![World Of Warcraft - Retail Screenshot 2020 11 03 - 03 01 32 50](https://user-images.githubusercontent.com/25525584/97961527-7b352800-1d81-11eb-8edd-e62e91bee61c.png)

There where it says "Watch Font Size".

**Comment by IrcDirk** [comment]
Please try latest Alpha release.

**Comment by commonterry** [comment]
Getting what looks like the same error with 9.0.1.1-5-g31fbbdb-alpha.

**Comment by IrcDirk** [comment]
Ok. Give me some time, maybe i can do something about it... U have all modules or only Quest?

**Comment by commonterry** [comment]
I have only the quest module. Thank you for your time and sorry to bother. Like I wrote in the original post, it still saves changes. I just have to reload UI to get the error to stop. I'm not sure why it's only happening to me even with all other addons disabled.

**Comment by IrcDirk** [comment]
Yeah maybe its not making Carbonite unusable but still is a bug ;)

**Comment by commonterry** [comment]
For what it's worth, the error also happens if I change the quest watch font itself or the watch font spacing.
