### ISSUE TITLE
WOTLK classic - Quest watch window is double windowed and only 1 can be adjusted ( the useless one)

### ISSUE THREAD

**Issue by Leonardpana01** [mikepauer/Carbonite.Quests#96]
On the quest watch window when you want to freely adjust the size is just adjusting a darker window on the background but the actual quest watch window shows the same with couple of quests in it that always changes the number (sometimes shows 2 quests and I have to scroll long way to the 10th quest for example by showing the last two , 9th and 10th) and has a scroll bar on it. What I want to have is freely adjustable window that as big as you make it more quests shows in it. For example if I have 10 quests, and i want to see all of them in same time I want to make the window bigger , but when I do that , the window gets bigger , right, but only the background and shows like 2-3 quests, or in this screen shot i managed to show 6 quests, but I don't know how as is always chaging the number and I have to scroll in order to see the last quest for example,  will drop a screen shot to show you what I mean. I checked all the option and still seems buggy and dooesn't work.. In TBC classic was working perfectly fine. I will show 2 examples 1 how should be ( basically how was before in 3.3.4  and 1 how is now). and yes I selected the option in setting for fixed sized window on and off but I can't make it work like it was before  . Thanks
![1234](https://user-images.githubusercontent.com/115345425/194700572-51de3c3d-eaab-4e07-a411-6a921e3d096c.jpg)
![12345](https://user-images.githubusercontent.com/115345425/194700573-ecf1dbd7-64f7-4a03-9aa1-a91003de8394.jpg)

**Comment by IrcDirk** [comment]
This is not WOTLK Classic repository. Please report all issues of Classic version of addon repostiotory => https://github.com/IrcDirk/Carbonite-Classic/issues
